FROM debian:11

RUN apt update
RUN apt install -y \
         git debhelper g++ make libspandsp-dev flite1-dev \
         libspeex-dev libgsm1-dev libopus-dev libssl-dev python3-dev \
         python3.9-dev \
	 python3-sip-dev openssl libev-dev libmysqlcppconn-dev libevent-dev \
	 libxml2-dev libcurl4-openssl-dev libhiredis-dev

WORKDIR /

RUN git clone --depth 1 --branch python3-rhel7 https://github.com/hecko/sems.git

WORKDIR /sems

RUN USE_SPANDSP=1 make
RUN USE_SPANDSP=1 make install

# Run SEMS with the specified configuration
CMD ["/usr/local/sbin/sems", "-E", "-f", "/usr/local/etc/sems/sems.conf"]
