FROM almalinux:9

RUN yum install -y epel-release \
    && dnf config-manager --set-enabled crb \
    && dnf install -y https://dev.mysql.com/get/mysql80-community-release-el9-1.noarch.rpm \
    && dnf install -y \
        git \
        cmake3 \
        make \
        gcc-c++ \
        libevent-devel \
        libev-devel \
        gsm-devel \
        opus-devel \
        speex-devel \
        openssl-devel \
        python3-devel \
        hiredis-devel \
        zlib-devel \
        libcurl-devel \
        spandsp-devel \
        man \
        mysql-connector-c++-devel \
        libsamplerate-devel \
        libmpg123-devel \
        lame-devel \
        flite-devel \
        codec2-devel \
        bcg729-devel \
        rpm-build \
        mysql-connector-c++ \
        which \
        python3-mysqlclient --nogpgcheck

WORKDIR /

RUN git clone --depth 1 --branch fb https://github.com/hecko/sems.git

# build RPMs from sources
RUN mkdir -p /root/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}
WORKDIR /sems
RUN make rpmtar
RUN rpmbuild -ba pkg/rpm/sems.spec
RUN ls -al /root/rpmbuild/RPMS

# install all SEMS RPMs
RUN rpm -i /root/rpmbuild/RPMS/x86_64/sems-*.rpm

# Run SEMS with the specified configuration
CMD ["/usr/local/sbin/sems", "-E", "-f", "/usr/local/etc/sems/sems.conf"]
