/*
 * Internal module API header file.
 *
 * Generated by SIP 4.1.1 (4.1.1-255) on Fri Feb  9 10:28:23 2007
 */

#ifndef _py_semsAPI_H
#define	_py_semsAPI_H


#include <sip.h>


/*
 * Convenient names to refer to the names of classes defined in this module.
 * These are part of the public API.
 */

#define	sipName_PySemsDialog	sipNm_py_sems_PySemsDialog
#define	sipName_AmSipDialog	sipNm_py_sems_AmSipDialog
#define	sipName_AmSipReply	sipNm_py_sems_AmSipReply
#define	sipName_AmSipRequest	sipNm_py_sems_AmSipRequest


/* Convenient names to call the SIP API. */
#define	sipConvertFromSliceObject(o,len,start,stop,step,slen)	PySlice_GetIndicesEx((PySliceObject *)(o),(len),(start),(stop),(step),(slen))
#define	sipIsSubClassInstance(o,wt)	PyObject_TypeCheck((o),(PyTypeObject *)(wt))

#define	sipMapStringToClass		sipAPI_py_sems -> api_map_string_to_class
#define	sipMapIntToClass		sipAPI_py_sems -> api_map_int_to_class
#define	sipMalloc			sipAPI_py_sems -> api_malloc
#define	sipFree				sipAPI_py_sems -> api_free
#define	sipBuildResult			sipAPI_py_sems -> api_build_result
#define	sipCallMethod			sipAPI_py_sems -> api_call_method
#define	sipParseResult			sipAPI_py_sems -> api_parse_result
#define	sipParseArgs			sipAPI_py_sems -> api_parse_args
#define	sipCommonCtor			sipAPI_py_sems -> api_common_ctor
#define	sipCommonDtor			sipAPI_py_sems -> api_common_dtor
#define	sipConvertFromSequenceIndex	sipAPI_py_sems -> api_convert_from_sequence_index
#define	sipConvertFromVoidPtr		sipAPI_py_sems -> api_convert_from_void_ptr
#define	sipConvertToCpp			sipAPI_py_sems -> api_convert_to_cpp
#define	sipConvertToVoidPtr		sipAPI_py_sems -> api_convert_to_void_ptr
#define	sipNoCtor			sipAPI_py_sems -> api_no_ctor
#define	sipNoFunction			sipAPI_py_sems -> api_no_function
#define	sipNoMethod			sipAPI_py_sems -> api_no_method
#define	sipBadClass			sipAPI_py_sems -> api_bad_class
#define	sipBadSetType			sipAPI_py_sems -> api_bad_set_type
#define	sipBadCatcherResult		sipAPI_py_sems -> api_bad_catcher_result
#define	sipTrace			sipAPI_py_sems -> api_trace
#define	sipTransfer			sipAPI_py_sems -> api_transfer
#define	sipGetWrapper			sipAPI_py_sems -> api_get_wrapper
#define	sipGetCppPtr			sipAPI_py_sems -> api_get_cpp_ptr
#define	sipGetComplexCppPtr		sipAPI_py_sems -> api_get_complex_cpp_ptr
#define	sipIsPyMethod			sipAPI_py_sems -> api_is_py_method
#define	sipMapCppToSelf			sipAPI_py_sems -> api_map_cpp_to_self
#define	sipMapCppToSelfSubClass		sipAPI_py_sems -> api_map_cpp_to_self_sub_class
#define	sipNewCppToSelf			sipAPI_py_sems -> api_new_cpp_to_self
#define	sipNewCppToSelfSubClass		sipAPI_py_sems -> api_new_cpp_to_self_sub_class
#define	sipCallHook			sipAPI_py_sems -> api_call_hook
#define	sipStartThread			sipAPI_py_sems -> api_start_thread
#define	sipEndThread			sipAPI_py_sems -> api_end_thread
#define	sipEmitSignal			sipAPI_py_sems -> api_emit_signal
#define	sipEmitToSlot			sipAPI_py_sems -> api_emit_to_slot
#define	sipConnectRx			sipAPI_py_sems -> api_connect_rx
#define	sipDisconnectRx			sipAPI_py_sems -> api_disconnect_rx
#define	sipGetSender			sipAPI_py_sems -> api_get_sender
#define	sipRaiseUnknownException	sipAPI_py_sems -> api_raise_unknown_exception
#define	sipRaiseClassException		sipAPI_py_sems -> api_raise_class_exception
#define	sipRaiseSubClassException	sipAPI_py_sems -> api_raise_sub_class_exception
#define	sipBadLengthForSlice		sipAPI_py_sems -> api_bad_length_for_slice
#define	sipClassName			sipAPI_py_sems -> api_class_name
#define	sipAddClassInstance		sipAPI_py_sems -> api_add_class_instance


/* The strings used by this module. */
extern char sipNm_py_sems_onOtherReply[];
extern char sipNm_py_sems_onOtherBye[];
extern char sipNm_py_sems_onDtmf[];
extern char sipNm_py_sems_onCancel[];
extern char sipNm_py_sems_onBye[];
extern char sipNm_py_sems_onSessionStart[];
extern char sipNm_py_sems_onInvite[];
extern char sipNm_py_sems_setStopped[];
extern char sipNm_py_sems_acceptAudio[];
extern char sipNm_py_sems_dlg[];
extern char sipNm_py_sems_PySemsDialog[];
extern char sipNm_py_sems_reinvite[];
extern char sipNm_py_sems_update[];
extern char sipNm_py_sems_cancel[];
extern char sipNm_py_sems_bye[];
extern char sipNm_py_sems_sendRequest[];
extern char sipNm_py_sems_reply[];
extern char sipNm_py_sems_updateStatus[];
extern char sipNm_py_sems_getContactHdr[];
extern char sipNm_py_sems_getStatus[];
extern char sipNm_py_sems_getUACTransPending[];
extern char sipNm_py_sems_setRoute[];
extern char sipNm_py_sems_getRoute[];
extern char sipNm_py_sems_local_party[];
extern char sipNm_py_sems_remote_party[];
extern char sipNm_py_sems_contact_uri[];
extern char sipNm_py_sems_remote_uri[];
extern char sipNm_py_sems_local_uri[];
extern char sipNm_py_sems_sip_port[];
extern char sipNm_py_sems_sip_ip[];
extern char sipNm_py_sems_Disconnecting[];
extern char sipNm_py_sems_Connected[];
extern char sipNm_py_sems_Pending[];
extern char sipNm_py_sems_Disconnected[];
extern char sipNm_py_sems_AmSipDialog[];
extern char sipNm_py_sems_local_tag[];
extern char sipNm_py_sems_remote_tag[];
extern char sipNm_py_sems_next_request_uri[];
extern char sipNm_py_sems_reason[];
extern char sipNm_py_sems_code[];
extern char sipNm_py_sems_AmSipReply[];
extern char sipNm_py_sems_getHeader[];
extern char sipNm_py_sems_key[];
extern char sipNm_py_sems_next_hop[];
extern char sipNm_py_sems_route[];
extern char sipNm_py_sems_body[];
extern char sipNm_py_sems_hdrs[];
extern char sipNm_py_sems_cseq[];
extern char sipNm_py_sems_to_tag[];
extern char sipNm_py_sems_from_tag[];
extern char sipNm_py_sems_callid[];
extern char sipNm_py_sems_to[];
extern char sipNm_py_sems_from[];
extern char sipNm_py_sems_from_uri[];
extern char sipNm_py_sems_r_uri[];
extern char sipNm_py_sems_port[];
extern char sipNm_py_sems_dstip[];
extern char sipNm_py_sems_domain[];
extern char sipNm_py_sems_user[];
extern char sipNm_py_sems_method[];
extern char sipNm_py_sems_cmd[];
extern char sipNm_py_sems_AmSipRequest[];
extern char sipNm_py_sems_string[];


/* The SIP API, this module's API and the APIs of any imported modules. */
extern const sipAPIDef *sipAPI_py_sems;
extern sipExportedModuleDef sipModuleAPI_py_sems;

#endif
