/*
 * Internal module API header file.
 *
 * Generated by SIP 4.5.2 (4.5.2) on Tue Feb 20 15:24:56 2007
 */

#ifndef _py_sems_libAPI_H
#define _py_sems_libAPI_H


#include <sip.h>
#line 3 "AmUtils.sip"
#include "AmUtils.h"
#line 15 "sipAPIpy_sems_lib.h"


/*
 * Convenient names to refer to the names of classes defined in this module.
 * These are part of the public API.
 */

#define sipName_PySemsDialog  sipNm_py_sems_lib_PySemsDialog
#define sipName_AmAudioFile  sipNm_py_sems_lib_AmAudioFile
#define sipName_AmAudioEvent  sipNm_py_sems_lib_AmAudioEvent
#define sipName_AmEvent  sipNm_py_sems_lib_AmEvent
#define sipName_AmSipDialog  sipNm_py_sems_lib_AmSipDialog
#define sipName_AmSipReply  sipNm_py_sems_lib_AmSipReply
#define sipName_AmSipRequest  sipNm_py_sems_lib_AmSipRequest


/* Convenient names to call the SIP API. */
#define sipConvertFromSliceObject(o,len,start,stop,step,slen)   PySlice_GetIndicesEx((PySliceObject *)(o),(len),(start),(stop),(step),(slen))
#define sipIsSubClassInstance(o,wt) PyObject_TypeCheck((o),(PyTypeObject *)(wt))

#define sipMapStringToClass         sipAPI_py_sems_lib->api_map_string_to_class
#define sipMapIntToClass            sipAPI_py_sems_lib->api_map_int_to_class
#define sipMalloc                   sipAPI_py_sems_lib->api_malloc
#define sipFree                     sipAPI_py_sems_lib->api_free
#define sipBuildResult              sipAPI_py_sems_lib->api_build_result
#define sipCallMethod               sipAPI_py_sems_lib->api_call_method
#define sipParseResult              sipAPI_py_sems_lib->api_parse_result
#define sipParseArgs                sipAPI_py_sems_lib->api_parse_args
#define sipParsePair                sipAPI_py_sems_lib->api_parse_pair
#define sipCommonCtor               sipAPI_py_sems_lib->api_common_ctor
#define sipCommonDtor               sipAPI_py_sems_lib->api_common_dtor
#define sipConvertFromSequenceIndex sipAPI_py_sems_lib->api_convert_from_sequence_index
#define sipConvertFromVoidPtr       sipAPI_py_sems_lib->api_convert_from_void_ptr
#define sipConvertToCpp             sipAPI_py_sems_lib->api_convert_to_cpp
#define sipConvertToVoidPtr         sipAPI_py_sems_lib->api_convert_to_void_ptr
#define sipNoFunction               sipAPI_py_sems_lib->api_no_function
#define sipNoMethod                 sipAPI_py_sems_lib->api_no_method
#define sipAbstractMethod           sipAPI_py_sems_lib->api_abstract_method
#define sipBadClass                 sipAPI_py_sems_lib->api_bad_class
#define sipBadSetType               sipAPI_py_sems_lib->api_bad_set_type
#define sipBadCatcherResult         sipAPI_py_sems_lib->api_bad_catcher_result
#define sipBadOperatorArg           sipAPI_py_sems_lib->api_bad_operator_arg
#define sipTrace                    sipAPI_py_sems_lib->api_trace
#define sipTransfer                 sipAPI_py_sems_lib->api_transfer
#define sipTransferBack             sipAPI_py_sems_lib->api_transfer_back
#define sipTransferTo               sipAPI_py_sems_lib->api_transfer_to
#define sipWrapper_Check            sipAPI_py_sems_lib->api_wrapper_check
#define sipGetWrapper               sipAPI_py_sems_lib->api_get_wrapper
#define sipGetCppPtr                sipAPI_py_sems_lib->api_get_cpp_ptr
#define sipGetComplexCppPtr         sipAPI_py_sems_lib->api_get_complex_cpp_ptr
#define sipIsPyMethod               sipAPI_py_sems_lib->api_is_py_method
#define sipCallHook                 sipAPI_py_sems_lib->api_call_hook
#define sipStartThread              sipAPI_py_sems_lib->api_start_thread
#define sipEndThread                sipAPI_py_sems_lib->api_end_thread
#define sipEmitSignal               sipAPI_py_sems_lib->api_emit_signal
#define sipConnectRx                sipAPI_py_sems_lib->api_connect_rx
#define sipDisconnectRx             sipAPI_py_sems_lib->api_disconnect_rx
#define sipGetSender                sipAPI_py_sems_lib->api_get_sender
#define sipRaiseUnknownException    sipAPI_py_sems_lib->api_raise_unknown_exception
#define sipRaiseClassException      sipAPI_py_sems_lib->api_raise_class_exception
#define sipRaiseSubClassException   sipAPI_py_sems_lib->api_raise_sub_class_exception
#define sipBadLengthForSlice        sipAPI_py_sems_lib->api_bad_length_for_slice
#define sipClassName                sipAPI_py_sems_lib->api_class_name
#define sipAddClassInstance         sipAPI_py_sems_lib->api_add_class_instance
#define sipAddMappedTypeInstance    sipAPI_py_sems_lib->api_add_mapped_type_instance
#define sipAddEnumInstance          sipAPI_py_sems_lib->api_add_enum_instance
#define sipConvertFromNamedEnum     sipAPI_py_sems_lib->api_convert_from_named_enum
#define sipGetAddress               sipAPI_py_sems_lib->api_get_address
#define sipFreeConnection           sipAPI_py_sems_lib->api_free_connection
#define sipEmitToSlot               sipAPI_py_sems_lib->api_emit_to_slot
#define sipSameConnection           sipAPI_py_sems_lib->api_same_connection
#define sipPySlotExtend             sipAPI_py_sems_lib->api_pyslot_extend
#define sipConvertRx                sipAPI_py_sems_lib->api_convert_rx
#define sipAddDelayedDtor           sipAPI_py_sems_lib->api_add_delayed_dtor
#define sipCanConvertToInstance     sipAPI_py_sems_lib->api_can_convert_to_instance
#define sipCanConvertToMappedType   sipAPI_py_sems_lib->api_can_convert_to_mapped_type
#define sipConvertToInstance        sipAPI_py_sems_lib->api_convert_to_instance
#define sipConvertToMappedType      sipAPI_py_sems_lib->api_convert_to_mapped_type
#define sipForceConvertToInstance   sipAPI_py_sems_lib->api_force_convert_to_instance
#define sipForceConvertToMappedType sipAPI_py_sems_lib->api_force_convert_to_mapped_type
#define sipReleaseInstance          sipAPI_py_sems_lib->api_release_instance
#define sipReleaseMappedType        sipAPI_py_sems_lib->api_release_mapped_type
#define sipConvertFromInstance      sipAPI_py_sems_lib->api_convert_from_instance
#define sipConvertFromNewInstance   sipAPI_py_sems_lib->api_convert_from_new_instance
#define sipConvertFromMappedType    sipAPI_py_sems_lib->api_convert_from_mapped_type
#define sipGetState                 sipAPI_py_sems_lib->api_get_state
#define sipFindMappedType           sipAPI_py_sems_lib->api_find_mapped_type
#define sipLong_AsUnsignedLong      sipAPI_py_sems_lib->api_long_as_unsigned_long
#define sipExportSymbol             sipAPI_py_sems_lib->api_export_symbol
#define sipImportSymbol             sipAPI_py_sems_lib->api_import_symbol
#define sipRegisterIntTypes         sipAPI_py_sems_lib->api_register_int_types


/* The strings used by this module. */
extern char sipNm_py_sems_lib_get_header_param[];
extern char sipNm_py_sems_lib_process[];
extern char sipNm_py_sems_lib_setInOut[];
extern char sipNm_py_sems_lib_setOutput[];
extern char sipNm_py_sems_lib_setInput[];
extern char sipNm_py_sems_lib_onDtmf[];
extern char sipNm_py_sems_lib_onBye[];
extern char sipNm_py_sems_lib_onCancel[];
extern char sipNm_py_sems_lib_onSessionStart[];
extern char sipNm_py_sems_lib_onInvite[];
extern char sipNm_py_sems_lib_setStopped[];
extern char sipNm_py_sems_lib_acceptAudio[];
extern char sipNm_py_sems_lib_dlg[];
extern char sipNm_py_sems_lib_PySemsDialog[];
extern char sipNm_py_sems_lib_getDataSize[];
extern char sipNm_py_sems_lib_close[];
extern char sipNm_py_sems_lib_rewind[];
extern char sipNm_py_sems_lib_open[];
extern char sipNm_py_sems_lib_setLoop[];
extern char sipNm_py_sems_lib_getLoop[];
extern char sipNm_py_sems_lib_Write[];
extern char sipNm_py_sems_lib_Read[];
extern char sipNm_py_sems_lib_AmAudioFile[];
extern char sipNm_py_sems_lib_cleared[];
extern char sipNm_py_sems_lib_noAudio[];
extern char sipNm_py_sems_lib_AmAudioEvent[];
extern char sipNm_py_sems_lib_processed[];
extern char sipNm_py_sems_lib_event_id[];
extern char sipNm_py_sems_lib_AmEvent[];
extern char sipNm_py_sems_lib_reinvite[];
extern char sipNm_py_sems_lib_update[];
extern char sipNm_py_sems_lib_cancel[];
extern char sipNm_py_sems_lib_bye[];
extern char sipNm_py_sems_lib_sendRequest[];
extern char sipNm_py_sems_lib_reply[];
extern char sipNm_py_sems_lib_updateStatus[];
extern char sipNm_py_sems_lib_getContactHdr[];
extern char sipNm_py_sems_lib_getStatus[];
extern char sipNm_py_sems_lib_getUACTransPending[];
extern char sipNm_py_sems_lib_setRoute[];
extern char sipNm_py_sems_lib_getRoute[];
extern char sipNm_py_sems_lib_local_party[];
extern char sipNm_py_sems_lib_remote_party[];
extern char sipNm_py_sems_lib_contact_uri[];
extern char sipNm_py_sems_lib_remote_uri[];
extern char sipNm_py_sems_lib_local_uri[];
extern char sipNm_py_sems_lib_sip_port[];
extern char sipNm_py_sems_lib_sip_ip[];
extern char sipNm_py_sems_lib_Disconnecting[];
extern char sipNm_py_sems_lib_Connected[];
extern char sipNm_py_sems_lib_Pending[];
extern char sipNm_py_sems_lib_Disconnected[];
extern char sipNm_py_sems_lib_AmSipDialog[];
extern char sipNm_py_sems_lib_local_tag[];
extern char sipNm_py_sems_lib_remote_tag[];
extern char sipNm_py_sems_lib_next_request_uri[];
extern char sipNm_py_sems_lib_reason[];
extern char sipNm_py_sems_lib_code[];
extern char sipNm_py_sems_lib_AmSipReply[];
extern char sipNm_py_sems_lib_getHeader[];
extern char sipNm_py_sems_lib_key[];
extern char sipNm_py_sems_lib_next_hop[];
extern char sipNm_py_sems_lib_route[];
extern char sipNm_py_sems_lib_body[];
extern char sipNm_py_sems_lib_hdrs[];
extern char sipNm_py_sems_lib_cseq[];
extern char sipNm_py_sems_lib_to_tag[];
extern char sipNm_py_sems_lib_from_tag[];
extern char sipNm_py_sems_lib_callid[];
extern char sipNm_py_sems_lib_to[];
extern char sipNm_py_sems_lib_from[];
extern char sipNm_py_sems_lib_from_uri[];
extern char sipNm_py_sems_lib_r_uri[];
extern char sipNm_py_sems_lib_port[];
extern char sipNm_py_sems_lib_dstip[];
extern char sipNm_py_sems_lib_domain[];
extern char sipNm_py_sems_lib_user[];
extern char sipNm_py_sems_lib_method[];
extern char sipNm_py_sems_lib_cmd[];
extern char sipNm_py_sems_lib_AmSipRequest[];
extern char sipNm_py_sems_lib_string[];


/* The SIP API, this module's API and the APIs of any imported modules. */
extern const sipAPIDef *sipAPI_py_sems_lib;
extern sipExportedModuleDef sipModuleAPI_py_sems_lib;

#endif
