/*
 * Interface header file.
 *
 * Generated by SIP 4.1.1 (4.1.1-255) on Fri Feb  9 10:28:23 2007
 */

#ifndef _py_semsAmSipReply_h
#define	_py_semsAmSipReply_h

#line 6 "AmSipReply.sip"
#include "../../../core/AmSipReply.h"
#line 13 "sippy_semsAmSipReply.h"

#include "sippy_semsstring.h"


#define	sipClass_AmSipReply	sipModuleAPI_py_sems.em_types[2]
#define	sipCast_AmSipReply	sipType_AmSipReply.td_cast
#define	sipForceConvertTo_AmSipReply	sipType_AmSipReply.td_fcto

extern sipTypeDef sipType_AmSipReply;

#endif
