/*
 * Interface wrapper code.
 *
 * Generated by SIP 4.5.2 (4.5.2) on Wed Mar 28 22:59:14 2007
 */

#include "sipAPIpy_sems_lib.h"
#include "sippy_sems_libPySemsB2ABDialog.h"

#include "sippy_sems_libAmSipDialog.h"
#include "sippy_sems_libPySemsB2ABDialog.h"
#include "sippy_sems_libAmEvent.h"
#include "sippy_sems_libAmAudioFile.h"
#include "sippy_sems_libAmSipRequest.h"
#include "sippy_sems_libstring.h"


sipPySemsB2ABDialog::sipPySemsB2ABDialog(): PySemsB2ABDialog(), sipPySelf(0)
{
    sipTrace(SIP_TRACE_CTORS,"sipPySemsB2ABDialog::sipPySemsB2ABDialog() (this=0x%08x)\n",this);

    sipCommonCtor(sipPyMethods,6);
}

sipPySemsB2ABDialog::~sipPySemsB2ABDialog()
{
    sipTrace(SIP_TRACE_DTORS,"sipPySemsB2ABDialog::~sipPySemsB2ABDialog() (this=0x%08x)\n",this);

    sipCommonDtor(sipPySelf);
}

void sipPySemsB2ABDialog::onInvite(const AmSipRequest& a0)
{
    sipTrace(SIP_TRACE_CATCHERS,"void sipPySemsB2ABDialog::onInvite(const AmSipRequest&) (this=0x%08x)\n",this);

    extern void sipVH_py_sems_lib_2(sip_gilstate_t,PyObject *,const AmSipRequest&);

    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[0],sipPySelf,NULL,sipNm_py_sems_lib_onInvite);

    if (!meth)
    {
        PySemsB2ABDialog::onInvite(a0);
        return;
    }

    sipVH_py_sems_lib_2(sipGILState,meth,a0);
}

void sipPySemsB2ABDialog::onSessionStart(const AmSipRequest& a0)
{
    sipTrace(SIP_TRACE_CATCHERS,"void sipPySemsB2ABDialog::onSessionStart(const AmSipRequest&) (this=0x%08x)\n",this);

    extern void sipVH_py_sems_lib_2(sip_gilstate_t,PyObject *,const AmSipRequest&);

    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[1],sipPySelf,NULL,sipNm_py_sems_lib_onSessionStart);

    if (!meth)
    {
        PySemsB2ABDialog::onSessionStart(a0);
        return;
    }

    sipVH_py_sems_lib_2(sipGILState,meth,a0);
}

void sipPySemsB2ABDialog::onCancel()
{
    sipTrace(SIP_TRACE_CATCHERS,"void sipPySemsB2ABDialog::onCancel() (this=0x%08x)\n",this);

    extern void sipVH_py_sems_lib_3(sip_gilstate_t,PyObject *);

    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[2],sipPySelf,NULL,sipNm_py_sems_lib_onCancel);

    if (!meth)
    {
        PySemsB2ABDialog::onCancel();
        return;
    }

    sipVH_py_sems_lib_3(sipGILState,meth);
}

void sipPySemsB2ABDialog::onBye(const AmSipRequest& a0)
{
    sipTrace(SIP_TRACE_CATCHERS,"void sipPySemsB2ABDialog::onBye(const AmSipRequest&) (this=0x%08x)\n",this);

    extern void sipVH_py_sems_lib_2(sip_gilstate_t,PyObject *,const AmSipRequest&);

    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[3],sipPySelf,NULL,sipNm_py_sems_lib_onBye);

    if (!meth)
    {
        PySemsB2ABDialog::onBye(a0);
        return;
    }

    sipVH_py_sems_lib_2(sipGILState,meth,a0);
}

void sipPySemsB2ABDialog::onDtmf(int a0,int a1)
{
    sipTrace(SIP_TRACE_CATCHERS,"void sipPySemsB2ABDialog::onDtmf(int,int) (this=0x%08x)\n",this);

    extern void sipVH_py_sems_lib_1(sip_gilstate_t,PyObject *,int,int);

    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[4],sipPySelf,NULL,sipNm_py_sems_lib_onDtmf);

    if (!meth)
    {
        PySemsB2ABDialog::onDtmf(a0,a1);
        return;
    }

    sipVH_py_sems_lib_1(sipGILState,meth,a0,a1);
}

void sipPySemsB2ABDialog::process(AmEvent *a0)
{
    sipTrace(SIP_TRACE_CATCHERS,"void sipPySemsB2ABDialog::process(AmEvent *) (this=0x%08x)\n",this);

    extern void sipVH_py_sems_lib_0(sip_gilstate_t,PyObject *,AmEvent *);

    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[5],sipPySelf,NULL,sipNm_py_sems_lib_process);

    if (!meth)
    {
        PySemsB2ABDialog::process(a0);
        return;
    }

    sipVH_py_sems_lib_0(sipGILState,meth,a0);
}


extern "C" {static PyObject *meth_PySemsB2ABDialog_acceptAudio(PyObject *, PyObject *);}
static PyObject *meth_PySemsB2ABDialog_acceptAudio(PyObject *sipSelf,PyObject *sipArgs)
{
    sipTrace(SIP_TRACE_METHODS,"meth_PySemsB2ABDialog_acceptAudio()\n");

    int sipArgsParsed = 0;

    {
        const string * a0;
        int a0State = 0;
        const string * a1;
        int a1State = 0;
        string * a2;
        PySemsB2ABDialog *sipCpp;

        if (sipParseArgs(&sipArgsParsed,sipArgs,"BM1M1",&sipSelf,sipClass_PySemsB2ABDialog,&sipCpp,sipMappedType_string,&a0,&a0State,sipMappedType_string,&a1,&a1State))
        {
            int sipRes;
            a2 = new string();

            sipRes = sipCpp->acceptAudio(*a0,*a1,a2);

            sipReleaseMappedType(const_cast<string *>(a0),sipMappedType_string,a0State);
            sipReleaseMappedType(const_cast<string *>(a1),sipMappedType_string,a1State);

            return sipBuildResult(0,"(iD)",sipRes,a2,sipMappedType_string,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipArgsParsed,sipNm_py_sems_lib_PySemsB2ABDialog,sipNm_py_sems_lib_acceptAudio);

    return NULL;
}


extern "C" {static PyObject *meth_PySemsB2ABDialog_setStopped(PyObject *, PyObject *);}
static PyObject *meth_PySemsB2ABDialog_setStopped(PyObject *sipSelf,PyObject *sipArgs)
{
    sipTrace(SIP_TRACE_METHODS,"meth_PySemsB2ABDialog_setStopped()\n");

    int sipArgsParsed = 0;

    {
        PySemsB2ABDialog *sipCpp;

        if (sipParseArgs(&sipArgsParsed,sipArgs,"B",&sipSelf,sipClass_PySemsB2ABDialog,&sipCpp))
        {
            sipCpp->setStopped();

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipArgsParsed,sipNm_py_sems_lib_PySemsB2ABDialog,sipNm_py_sems_lib_setStopped);

    return NULL;
}


extern "C" {static PyObject *meth_PySemsB2ABDialog_onInvite(PyObject *, PyObject *);}
static PyObject *meth_PySemsB2ABDialog_onInvite(PyObject *sipSelf,PyObject *sipArgs)
{
    sipTrace(SIP_TRACE_METHODS,"meth_PySemsB2ABDialog_onInvite()\n");

    int sipArgsParsed = 0;
    bool sipSelfWasArg = !sipSelf;

    {
        const AmSipRequest * a0;
        PySemsB2ABDialog *sipCpp;

        if (sipParseArgs(&sipArgsParsed,sipArgs,"BJA",&sipSelf,sipClass_PySemsB2ABDialog,&sipCpp,sipClass_AmSipRequest,&a0))
        {
            (sipSelfWasArg ? sipCpp->PySemsB2ABDialog::onInvite(*a0) : sipCpp->onInvite(*a0));

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipArgsParsed,sipNm_py_sems_lib_PySemsB2ABDialog,sipNm_py_sems_lib_onInvite);

    return NULL;
}


extern "C" {static PyObject *meth_PySemsB2ABDialog_onSessionStart(PyObject *, PyObject *);}
static PyObject *meth_PySemsB2ABDialog_onSessionStart(PyObject *sipSelf,PyObject *sipArgs)
{
    sipTrace(SIP_TRACE_METHODS,"meth_PySemsB2ABDialog_onSessionStart()\n");

    int sipArgsParsed = 0;
    bool sipSelfWasArg = !sipSelf;

    {
        const AmSipRequest * a0;
        PySemsB2ABDialog *sipCpp;

        if (sipParseArgs(&sipArgsParsed,sipArgs,"BJA",&sipSelf,sipClass_PySemsB2ABDialog,&sipCpp,sipClass_AmSipRequest,&a0))
        {
            (sipSelfWasArg ? sipCpp->PySemsB2ABDialog::onSessionStart(*a0) : sipCpp->onSessionStart(*a0));

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipArgsParsed,sipNm_py_sems_lib_PySemsB2ABDialog,sipNm_py_sems_lib_onSessionStart);

    return NULL;
}


extern "C" {static PyObject *meth_PySemsB2ABDialog_onCancel(PyObject *, PyObject *);}
static PyObject *meth_PySemsB2ABDialog_onCancel(PyObject *sipSelf,PyObject *sipArgs)
{
    sipTrace(SIP_TRACE_METHODS,"meth_PySemsB2ABDialog_onCancel()\n");

    int sipArgsParsed = 0;
    bool sipSelfWasArg = !sipSelf;

    {
        PySemsB2ABDialog *sipCpp;

        if (sipParseArgs(&sipArgsParsed,sipArgs,"B",&sipSelf,sipClass_PySemsB2ABDialog,&sipCpp))
        {
            (sipSelfWasArg ? sipCpp->PySemsB2ABDialog::onCancel() : sipCpp->onCancel());

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipArgsParsed,sipNm_py_sems_lib_PySemsB2ABDialog,sipNm_py_sems_lib_onCancel);

    return NULL;
}


extern "C" {static PyObject *meth_PySemsB2ABDialog_onBye(PyObject *, PyObject *);}
static PyObject *meth_PySemsB2ABDialog_onBye(PyObject *sipSelf,PyObject *sipArgs)
{
    sipTrace(SIP_TRACE_METHODS,"meth_PySemsB2ABDialog_onBye()\n");

    int sipArgsParsed = 0;
    bool sipSelfWasArg = !sipSelf;

    {
        const AmSipRequest * a0;
        PySemsB2ABDialog *sipCpp;

        if (sipParseArgs(&sipArgsParsed,sipArgs,"BJA",&sipSelf,sipClass_PySemsB2ABDialog,&sipCpp,sipClass_AmSipRequest,&a0))
        {
            (sipSelfWasArg ? sipCpp->PySemsB2ABDialog::onBye(*a0) : sipCpp->onBye(*a0));

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipArgsParsed,sipNm_py_sems_lib_PySemsB2ABDialog,sipNm_py_sems_lib_onBye);

    return NULL;
}


extern "C" {static PyObject *meth_PySemsB2ABDialog_onDtmf(PyObject *, PyObject *);}
static PyObject *meth_PySemsB2ABDialog_onDtmf(PyObject *sipSelf,PyObject *sipArgs)
{
    sipTrace(SIP_TRACE_METHODS,"meth_PySemsB2ABDialog_onDtmf()\n");

    int sipArgsParsed = 0;
    bool sipSelfWasArg = !sipSelf;

    {
        int a0;
        int a1;
        PySemsB2ABDialog *sipCpp;

        if (sipParseArgs(&sipArgsParsed,sipArgs,"Bii",&sipSelf,sipClass_PySemsB2ABDialog,&sipCpp,&a0,&a1))
        {
            (sipSelfWasArg ? sipCpp->PySemsB2ABDialog::onDtmf(a0,a1) : sipCpp->onDtmf(a0,a1));

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipArgsParsed,sipNm_py_sems_lib_PySemsB2ABDialog,sipNm_py_sems_lib_onDtmf);

    return NULL;
}


extern "C" {static PyObject *meth_PySemsB2ABDialog_setInput(PyObject *, PyObject *);}
static PyObject *meth_PySemsB2ABDialog_setInput(PyObject *sipSelf,PyObject *sipArgs)
{
    sipTrace(SIP_TRACE_METHODS,"meth_PySemsB2ABDialog_setInput()\n");

    int sipArgsParsed = 0;

    {
        AmAudioFile * a0;
        PySemsB2ABDialog *sipCpp;

        if (sipParseArgs(&sipArgsParsed,sipArgs,"BJ@",&sipSelf,sipClass_PySemsB2ABDialog,&sipCpp,sipClass_AmAudioFile,&a0))
        {
            sipCpp->setInput(a0);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipArgsParsed,sipNm_py_sems_lib_PySemsB2ABDialog,sipNm_py_sems_lib_setInput);

    return NULL;
}


extern "C" {static PyObject *meth_PySemsB2ABDialog_setOutput(PyObject *, PyObject *);}
static PyObject *meth_PySemsB2ABDialog_setOutput(PyObject *sipSelf,PyObject *sipArgs)
{
    sipTrace(SIP_TRACE_METHODS,"meth_PySemsB2ABDialog_setOutput()\n");

    int sipArgsParsed = 0;

    {
        AmAudioFile * a0;
        PySemsB2ABDialog *sipCpp;

        if (sipParseArgs(&sipArgsParsed,sipArgs,"BJ@",&sipSelf,sipClass_PySemsB2ABDialog,&sipCpp,sipClass_AmAudioFile,&a0))
        {
            sipCpp->setOutput(a0);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipArgsParsed,sipNm_py_sems_lib_PySemsB2ABDialog,sipNm_py_sems_lib_setOutput);

    return NULL;
}


extern "C" {static PyObject *meth_PySemsB2ABDialog_setInOut(PyObject *, PyObject *);}
static PyObject *meth_PySemsB2ABDialog_setInOut(PyObject *sipSelf,PyObject *sipArgs)
{
    sipTrace(SIP_TRACE_METHODS,"meth_PySemsB2ABDialog_setInOut()\n");

    int sipArgsParsed = 0;

    {
        AmAudioFile * a0;
        AmAudioFile * a1;
        PySemsB2ABDialog *sipCpp;

        if (sipParseArgs(&sipArgsParsed,sipArgs,"BJ@J@",&sipSelf,sipClass_PySemsB2ABDialog,&sipCpp,sipClass_AmAudioFile,&a0,sipClass_AmAudioFile,&a1))
        {
            sipCpp->setInOut(a0,a1);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipArgsParsed,sipNm_py_sems_lib_PySemsB2ABDialog,sipNm_py_sems_lib_setInOut);

    return NULL;
}


extern "C" {static PyObject *meth_PySemsB2ABDialog_process(PyObject *, PyObject *);}
static PyObject *meth_PySemsB2ABDialog_process(PyObject *sipSelf,PyObject *sipArgs)
{
    sipTrace(SIP_TRACE_METHODS,"meth_PySemsB2ABDialog_process()\n");

    int sipArgsParsed = 0;
    bool sipSelfWasArg = !sipSelf;

    {
        AmEvent * a0;
        PySemsB2ABDialog *sipCpp;

        if (sipParseArgs(&sipArgsParsed,sipArgs,"BJ@",&sipSelf,sipClass_PySemsB2ABDialog,&sipCpp,sipClass_AmEvent,&a0))
        {
            (sipSelfWasArg ? sipCpp->PySemsB2ABDialog::process(a0) : sipCpp->process(a0));

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipArgsParsed,sipNm_py_sems_lib_PySemsB2ABDialog,sipNm_py_sems_lib_process);

    return NULL;
}


/* Cast a pointer to a type somewhere in its superclass hierarchy. */
extern "C" {static void *cast_PySemsB2ABDialog(void *, sipWrapperType *);}
static void *cast_PySemsB2ABDialog(void *ptr,sipWrapperType *targetClass)
{
    if (targetClass == sipClass_PySemsB2ABDialog)
        return ptr;

    return NULL;
}


/* Call the instance's destructor. */
extern "C" {static void release_PySemsB2ABDialog(void *, int);}
static void release_PySemsB2ABDialog(void *ptr,int state)
{
    if (state & SIP_DERIVED_CLASS)
        delete reinterpret_cast<sipPySemsB2ABDialog *>(ptr);
    else
        delete reinterpret_cast<PySemsB2ABDialog *>(ptr);
}


extern "C" {static void dealloc_PySemsB2ABDialog(sipWrapper *);}
static void dealloc_PySemsB2ABDialog(sipWrapper *sipSelf)
{
    sipTrace(SIP_TRACE_DEALLOCS,"dealloc_PySemsB2ABDialog()\n");

    if (sipIsDerived(sipSelf))
        reinterpret_cast<sipPySemsB2ABDialog *>(sipSelf->u.cppPtr)->sipPySelf = NULL;

    if (sipIsPyOwned(sipSelf))
    {
#line 17 "PySemsB2ABDialog.sip"
    fprintf(stderr,"------------- dealloc_PySemsB2ABDialog ----------\n");
#line 500 "sippy_sems_libPySemsB2ABDialog.cpp"

        release_PySemsB2ABDialog(sipSelf->u.cppPtr,sipSelf->flags);
    }
}


extern "C" {static void *init_PySemsB2ABDialog(sipWrapper *, PyObject *, sipWrapper **, int *);}
static void *init_PySemsB2ABDialog(sipWrapper *sipSelf,PyObject *sipArgs,sipWrapper **,int *sipArgsParsed)
{
    sipPySemsB2ABDialog *sipCpp = 0;

    sipTrace(SIP_TRACE_INITS,"init_PySemsB2ABDialog()\n");

    if (!sipCpp)
    {
        if (sipParseArgs(sipArgsParsed,sipArgs,""))
        {
            sipCpp = new sipPySemsB2ABDialog();
        }
    }

    if (sipCpp)
        sipCpp->sipPySelf = sipSelf;

    return sipCpp;
}


extern "C" {static PyObject *var_PySemsB2ABDialog_dlg(PyObject *, PyObject *);}
static PyObject *var_PySemsB2ABDialog_dlg(PyObject *sipSelf,PyObject *sipPy)
{
    int sipIsErr = 0;
   AmSipDialog *sipVal;
    PySemsB2ABDialog *sipCpp = reinterpret_cast<PySemsB2ABDialog *>(sipGetCppPtr((sipWrapper *)sipSelf,sipClass_PySemsB2ABDialog));

    if (!sipCpp)
        return NULL;

    if (sipPy == NULL)
    {
        sipVal = &sipCpp->dlg;

        sipPy = sipConvertFromInstance(sipVal,sipClass_AmSipDialog,NULL);

        return sipPy;
    }

    sipVal = reinterpret_cast<AmSipDialog *>(sipForceConvertToInstance(sipPy,sipClass_AmSipDialog,NULL,SIP_NOT_NONE,NULL,&sipIsErr));

    if (sipIsErr)
        return NULL;

    sipCpp->dlg = *sipVal;

    Py_INCREF(Py_None);
    return Py_None;
}

PyMethodDef variables_PySemsB2ABDialog[] = {
    {sipNm_py_sems_lib_dlg, var_PySemsB2ABDialog_dlg, 0, NULL},
    {0, 0, 0, 0}
};


extern "C" {static void *forceConvertTo_PySemsB2ABDialog(PyObject *, int *);}
static void *forceConvertTo_PySemsB2ABDialog(PyObject *valobj,int *iserrp)
{
    if (*iserrp || valobj == NULL)
        return NULL;

    if (valobj == Py_None || sipIsSubClassInstance(valobj,sipClass_PySemsB2ABDialog))
        return sipConvertToCpp(valobj,sipClass_PySemsB2ABDialog,iserrp);

    sipBadClass(sipNm_py_sems_lib_PySemsB2ABDialog);

    *iserrp = 1;

    return NULL;
}


static PyMethodDef methods_PySemsB2ABDialog[] = {
    {sipNm_py_sems_lib_acceptAudio, meth_PySemsB2ABDialog_acceptAudio, METH_VARARGS, NULL},
    {sipNm_py_sems_lib_onBye, meth_PySemsB2ABDialog_onBye, METH_VARARGS, NULL},
    {sipNm_py_sems_lib_onCancel, meth_PySemsB2ABDialog_onCancel, METH_VARARGS, NULL},
    {sipNm_py_sems_lib_onDtmf, meth_PySemsB2ABDialog_onDtmf, METH_VARARGS, NULL},
    {sipNm_py_sems_lib_onInvite, meth_PySemsB2ABDialog_onInvite, METH_VARARGS, NULL},
    {sipNm_py_sems_lib_onSessionStart, meth_PySemsB2ABDialog_onSessionStart, METH_VARARGS, NULL},
    {sipNm_py_sems_lib_process, meth_PySemsB2ABDialog_process, METH_VARARGS, NULL},
    {sipNm_py_sems_lib_setInOut, meth_PySemsB2ABDialog_setInOut, METH_VARARGS, NULL},
    {sipNm_py_sems_lib_setInput, meth_PySemsB2ABDialog_setInput, METH_VARARGS, NULL},
    {sipNm_py_sems_lib_setOutput, meth_PySemsB2ABDialog_setOutput, METH_VARARGS, NULL},
    {sipNm_py_sems_lib_setStopped, meth_PySemsB2ABDialog_setStopped, METH_VARARGS, NULL}
};


sipTypeDef sipType_py_sems_lib_PySemsB2ABDialog = {
    0,
    0,
    "py_sems_lib.PySemsB2ABDialog",
    0,
    {0, 0, 1},
    0,
    0,
    11, methods_PySemsB2ABDialog,
    0, 0,
    variables_PySemsB2ABDialog,
    init_PySemsB2ABDialog,
    0,
    0,
    0,
    0,
    0,
    0,
    dealloc_PySemsB2ABDialog,
    cast_PySemsB2ABDialog,
    release_PySemsB2ABDialog,
    forceConvertTo_PySemsB2ABDialog,
    0,
    0,
    {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    0
};
