/*
 * Interface wrapper code.
 *
 * Generated by SIP 4.1.1 (4.1.1-255) on Fri Feb  9 10:28:23 2007
 */

#include "sipAPIpy_sems.h"
#include "sippy_semsPySemsDialog.h"

sipPySemsDialog::sipPySemsDialog(): PySemsDialog(), sipPySelf(0)
{
	sipCommonCtor(sipPyMethods,7);
}

sipPySemsDialog::~sipPySemsDialog()
{
	sipCommonDtor(sipPySelf);
}

void sipPySemsDialog::onInvite(const AmSipRequest& a0)
{
	extern void sipVH_py_sems_1(sip_gilstate_t,PyObject *,const AmSipRequest&);

	sip_gilstate_t sipGILState;
	PyObject *meth;

	meth = sipIsPyMethod(&sipGILState,&sipPyMethods[0],sipPySelf,NULL,sipNm_py_sems_onInvite);

	if (!meth)
	{
		PySemsDialog::onInvite(a0);
		return;
	}

	sipVH_py_sems_1(sipGILState,meth,a0);
}

void sipPySemsDialog::onSessionStart(const AmSipRequest& a0)
{
	extern void sipVH_py_sems_1(sip_gilstate_t,PyObject *,const AmSipRequest&);

	sip_gilstate_t sipGILState;
	PyObject *meth;

	meth = sipIsPyMethod(&sipGILState,&sipPyMethods[1],sipPySelf,NULL,sipNm_py_sems_onSessionStart);

	if (!meth)
	{
		PySemsDialog::onSessionStart(a0);
		return;
	}

	sipVH_py_sems_1(sipGILState,meth,a0);
}

void sipPySemsDialog::onBye(const AmSipRequest& a0)
{
	extern void sipVH_py_sems_1(sip_gilstate_t,PyObject *,const AmSipRequest&);

	sip_gilstate_t sipGILState;
	PyObject *meth;

	meth = sipIsPyMethod(&sipGILState,&sipPyMethods[2],sipPySelf,NULL,sipNm_py_sems_onBye);

	if (!meth)
	{
		PySemsDialog::onBye(a0);
		return;
	}

	sipVH_py_sems_1(sipGILState,meth,a0);
}

void sipPySemsDialog::onCancel()
{
	extern void sipVH_py_sems_3(sip_gilstate_t,PyObject *);

	sip_gilstate_t sipGILState;
	PyObject *meth;

	meth = sipIsPyMethod(&sipGILState,&sipPyMethods[3],sipPySelf,NULL,sipNm_py_sems_onCancel);

	if (!meth)
	{
		PySemsDialog::onCancel();
		return;
	}

	sipVH_py_sems_3(sipGILState,meth);
}

void sipPySemsDialog::onDtmf(int a0,int a1)
{
	extern void sipVH_py_sems_2(sip_gilstate_t,PyObject *,int,int);

	sip_gilstate_t sipGILState;
	PyObject *meth;

	meth = sipIsPyMethod(&sipGILState,&sipPyMethods[4],sipPySelf,NULL,sipNm_py_sems_onDtmf);

	if (!meth)
	{
		PySemsDialog::onDtmf(a0,a1);
		return;
	}

	sipVH_py_sems_2(sipGILState,meth,a0,a1);
}

void sipPySemsDialog::onOtherBye(const AmSipRequest& a0)
{
	extern void sipVH_py_sems_1(sip_gilstate_t,PyObject *,const AmSipRequest&);

	sip_gilstate_t sipGILState;
	PyObject *meth;

	meth = sipIsPyMethod(&sipGILState,&sipPyMethods[5],sipPySelf,NULL,sipNm_py_sems_onOtherBye);

	if (!meth)
	{
		PySemsDialog::onOtherBye(a0);
		return;
	}

	sipVH_py_sems_1(sipGILState,meth,a0);
}

void sipPySemsDialog::onOtherReply(const AmSipReply& a0)
{
	extern void sipVH_py_sems_0(sip_gilstate_t,PyObject *,const AmSipReply&);

	sip_gilstate_t sipGILState;
	PyObject *meth;

	meth = sipIsPyMethod(&sipGILState,&sipPyMethods[6],sipPySelf,NULL,sipNm_py_sems_onOtherReply);

	if (!meth)
	{
		PySemsDialog::onOtherReply(a0);
		return;
	}

	sipVH_py_sems_0(sipGILState,meth,a0);
}


static PyObject *meth_PySemsDialog_acceptAudio(PyObject *sipSelf,PyObject *sipArgs)
{
	int sipArgsParsed = 0;

	{
		const string * a0;
		int a0IsTemp = 0;
		const string * a1;
		int a1IsTemp = 0;
		string * a2;
		PySemsDialog *sipCpp;

		if (sipParseArgs(&sipArgsParsed,sipArgs,"mM1M1",sipSelf,sipClass_PySemsDialog,&sipCpp,sipConvertTo_string,&a0,&a0IsTemp,sipConvertTo_string,&a1,&a1IsTemp))
		{
			int sipRes;
			a2 = new string();

			sipRes = sipCpp -> PySemsDialog::acceptAudio(*a0,*a1,a2);

			if (a0IsTemp)
				delete const_cast<string *>(a0);

			if (a1IsTemp)
				delete const_cast<string *>(a1);

			return sipBuildResult(0,"(iT)",sipRes,a2,sipConvertFrom_string);
		}
	}

	/* Raise an exception if the arguments couldn't be parsed. */
	sipNoMethod(sipArgsParsed,sipNm_py_sems_PySemsDialog,sipNm_py_sems_acceptAudio);

	return NULL;
}


static PyObject *meth_PySemsDialog_setStopped(PyObject *sipSelf,PyObject *sipArgs)
{
	int sipArgsParsed = 0;

	{
		PySemsDialog *sipCpp;

		if (sipParseArgs(&sipArgsParsed,sipArgs,"m",sipSelf,sipClass_PySemsDialog,&sipCpp))
		{
			sipCpp -> PySemsDialog::setStopped();

			Py_INCREF(Py_None);
			return Py_None;
		}
	}

	/* Raise an exception if the arguments couldn't be parsed. */
	sipNoMethod(sipArgsParsed,sipNm_py_sems_PySemsDialog,sipNm_py_sems_setStopped);

	return NULL;
}


static PyObject *meth_PySemsDialog_onInvite(PyObject *sipSelf,PyObject *sipArgs)
{
	int sipArgsParsed = 0;

	{
		const AmSipRequest * a0;
		PySemsDialog *sipCpp;

		if (sipParseArgs(&sipArgsParsed,sipArgs,"mJ1",sipSelf,sipClass_PySemsDialog,&sipCpp,sipClass_AmSipRequest,&a0))
		{
			sipCpp -> PySemsDialog::onInvite(*a0);

			Py_INCREF(Py_None);
			return Py_None;
		}
	}

	/* Raise an exception if the arguments couldn't be parsed. */
	sipNoMethod(sipArgsParsed,sipNm_py_sems_PySemsDialog,sipNm_py_sems_onInvite);

	return NULL;
}


static PyObject *meth_PySemsDialog_onSessionStart(PyObject *sipSelf,PyObject *sipArgs)
{
	int sipArgsParsed = 0;

	{
		const AmSipRequest * a0;
		PySemsDialog *sipCpp;

		if (sipParseArgs(&sipArgsParsed,sipArgs,"mJ1",sipSelf,sipClass_PySemsDialog,&sipCpp,sipClass_AmSipRequest,&a0))
		{
			sipCpp -> PySemsDialog::onSessionStart(*a0);

			Py_INCREF(Py_None);
			return Py_None;
		}
	}

	/* Raise an exception if the arguments couldn't be parsed. */
	sipNoMethod(sipArgsParsed,sipNm_py_sems_PySemsDialog,sipNm_py_sems_onSessionStart);

	return NULL;
}


static PyObject *meth_PySemsDialog_onBye(PyObject *sipSelf,PyObject *sipArgs)
{
	int sipArgsParsed = 0;

	{
		const AmSipRequest * a0;
		PySemsDialog *sipCpp;

		if (sipParseArgs(&sipArgsParsed,sipArgs,"mJ1",sipSelf,sipClass_PySemsDialog,&sipCpp,sipClass_AmSipRequest,&a0))
		{
			sipCpp -> PySemsDialog::onBye(*a0);

			Py_INCREF(Py_None);
			return Py_None;
		}
	}

	/* Raise an exception if the arguments couldn't be parsed. */
	sipNoMethod(sipArgsParsed,sipNm_py_sems_PySemsDialog,sipNm_py_sems_onBye);

	return NULL;
}


static PyObject *meth_PySemsDialog_onCancel(PyObject *sipSelf,PyObject *sipArgs)
{
	int sipArgsParsed = 0;

	{
		PySemsDialog *sipCpp;

		if (sipParseArgs(&sipArgsParsed,sipArgs,"m",sipSelf,sipClass_PySemsDialog,&sipCpp))
		{
			sipCpp -> PySemsDialog::onCancel();

			Py_INCREF(Py_None);
			return Py_None;
		}
	}

	/* Raise an exception if the arguments couldn't be parsed. */
	sipNoMethod(sipArgsParsed,sipNm_py_sems_PySemsDialog,sipNm_py_sems_onCancel);

	return NULL;
}


static PyObject *meth_PySemsDialog_onDtmf(PyObject *sipSelf,PyObject *sipArgs)
{
	int sipArgsParsed = 0;

	{
		int a0;
		int a1;
		PySemsDialog *sipCpp;

		if (sipParseArgs(&sipArgsParsed,sipArgs,"mii",sipSelf,sipClass_PySemsDialog,&sipCpp,&a0,&a1))
		{
			sipCpp -> PySemsDialog::onDtmf(a0,a1);

			Py_INCREF(Py_None);
			return Py_None;
		}
	}

	/* Raise an exception if the arguments couldn't be parsed. */
	sipNoMethod(sipArgsParsed,sipNm_py_sems_PySemsDialog,sipNm_py_sems_onDtmf);

	return NULL;
}


static PyObject *meth_PySemsDialog_onOtherBye(PyObject *sipSelf,PyObject *sipArgs)
{
	int sipArgsParsed = 0;

	{
		const AmSipRequest * a0;
		PySemsDialog *sipCpp;

		if (sipParseArgs(&sipArgsParsed,sipArgs,"mJ1",sipSelf,sipClass_PySemsDialog,&sipCpp,sipClass_AmSipRequest,&a0))
		{
			sipCpp -> PySemsDialog::onOtherBye(*a0);

			Py_INCREF(Py_None);
			return Py_None;
		}
	}

	/* Raise an exception if the arguments couldn't be parsed. */
	sipNoMethod(sipArgsParsed,sipNm_py_sems_PySemsDialog,sipNm_py_sems_onOtherBye);

	return NULL;
}


static PyObject *meth_PySemsDialog_onOtherReply(PyObject *sipSelf,PyObject *sipArgs)
{
	int sipArgsParsed = 0;

	{
		const AmSipReply * a0;
		PySemsDialog *sipCpp;

		if (sipParseArgs(&sipArgsParsed,sipArgs,"mJ1",sipSelf,sipClass_PySemsDialog,&sipCpp,sipClass_AmSipReply,&a0))
		{
			sipCpp -> PySemsDialog::onOtherReply(*a0);

			Py_INCREF(Py_None);
			return Py_None;
		}
	}

	/* Raise an exception if the arguments couldn't be parsed. */
	sipNoMethod(sipArgsParsed,sipNm_py_sems_PySemsDialog,sipNm_py_sems_onOtherReply);

	return NULL;
}


/* Cast a pointer to a type somewhere in its superclass hierarchy. */
static void *cast_PySemsDialog(void *ptr,sipWrapperType *targetClass)
{
	if (targetClass == sipClass_PySemsDialog)
		return ptr;

	return NULL;
}


static void dealloc_PySemsDialog(sipWrapper *sipSelf)
{
	if (!sipIsSimple(sipSelf))
		reinterpret_cast<sipPySemsDialog *>(sipSelf -> u.cppPtr) -> sipPySelf = NULL;

	if (sipIsPyOwned(sipSelf))
	{
		if (!sipIsSimple(sipSelf))
			delete reinterpret_cast<sipPySemsDialog *>(sipSelf -> u.cppPtr);
		else
			delete reinterpret_cast<PySemsDialog *>(sipSelf -> u.cppPtr);
	}
}


static void *init_PySemsDialog(sipWrapper *sipSelf,PyObject *sipArgs,int *)
{
	int sipArgsParsed = 0;
	sipPySemsDialog *sipCpp = 0;

	if (!sipCpp)
	{
		if (sipParseArgs(&sipArgsParsed,sipArgs,""))
		{
			sipCpp = new sipPySemsDialog();
		}
	}

	if (!sipCpp)
	{
		sipNoCtor(sipArgsParsed,sipNm_py_sems_PySemsDialog);
		return 0;
	}

	sipCpp -> sipPySelf = sipSelf;

	return sipCpp;
}


static PyObject *var_PySemsDialog_dlg(PyObject *sipSelf,PyObject *valobj)
{
	int iserr = 0;
	AmSipDialog *val;
	PySemsDialog *sipCpp = reinterpret_cast<PySemsDialog *>(sipGetCppPtr((sipWrapper *)sipSelf,sipClass_PySemsDialog));

	if (!sipCpp)
		return NULL;

	if (valobj == NULL)
	{
		val = &sipCpp -> dlg;

		valobj = sipMapCppToSelf(val,sipClass_AmSipDialog);

		return valobj;
	}

	val = reinterpret_cast<AmSipDialog *>(sipForceConvertTo_AmSipDialog(valobj,&iserr));

	if (iserr)
	{
		sipBadSetType(sipNm_py_sems_PySemsDialog,sipNm_py_sems_dlg);
		return NULL;
	}

	sipCpp -> dlg = *val;

	Py_INCREF(Py_None);
	return Py_None;
}

PyMethodDef variables_PySemsDialog[] = {
	{sipNm_py_sems_dlg, var_PySemsDialog_dlg, 0, NULL},
	{0, 0, 0, 0}
};


static void *forceConvertTo_PySemsDialog(PyObject *valobj,int *iserrp)
{
	if (*iserrp || valobj == NULL)
		return NULL;

	if (valobj == Py_None || sipIsSubClassInstance(valobj,sipClass_PySemsDialog))
		return sipConvertToCpp(valobj,sipClass_PySemsDialog,iserrp);

	sipBadClass(sipNm_py_sems_PySemsDialog);

	*iserrp = 1;

	return NULL;
}


static PyMethodDef methods_PySemsDialog[] = {
	{sipNm_py_sems_acceptAudio, meth_PySemsDialog_acceptAudio, METH_VARARGS, NULL},
	{sipNm_py_sems_onBye, meth_PySemsDialog_onBye, METH_VARARGS, NULL},
	{sipNm_py_sems_onCancel, meth_PySemsDialog_onCancel, METH_VARARGS, NULL},
	{sipNm_py_sems_onDtmf, meth_PySemsDialog_onDtmf, METH_VARARGS, NULL},
	{sipNm_py_sems_onInvite, meth_PySemsDialog_onInvite, METH_VARARGS, NULL},
	{sipNm_py_sems_onOtherBye, meth_PySemsDialog_onOtherBye, METH_VARARGS, NULL},
	{sipNm_py_sems_onOtherReply, meth_PySemsDialog_onOtherReply, METH_VARARGS, NULL},
	{sipNm_py_sems_onSessionStart, meth_PySemsDialog_onSessionStart, METH_VARARGS, NULL},
	{sipNm_py_sems_setStopped, meth_PySemsDialog_setStopped, METH_VARARGS, NULL}
};


/* The main type data structure. */
sipTypeDef sipType_PySemsDialog = {
	0,
	"py_sems.PySemsDialog",
	-1,
	0,
	0,
	9, methods_PySemsDialog,
	0, 0,
	variables_PySemsDialog,
	init_PySemsDialog,
	dealloc_PySemsDialog,
	cast_PySemsDialog,
	forceConvertTo_PySemsDialog,
	0,
	0,
	0,
	{0, 0, 0, 0, 0, 0}
};
