/*
 * Interface header file.
 *
 * Generated by SIP 4.5.2 (4.5.2) on Wed Mar 28 22:59:14 2007
 */

#ifndef _py_sems_libAmAudioFile_h
#define _py_sems_libAmAudioFile_h

#line 51 "AmAudio.sip"
#include "../../../core/AmAudio.h"
#line 13 "sippy_sems_libAmAudioFile.h"

#define sipClass_AmAudioFile             sipModuleAPI_py_sems_lib.em_types[3]
#define sipCast_AmAudioFile              sipType_py_sems_lib_AmAudioFile.td_cast
#define sipForceConvertTo_AmAudioFile    sipType_py_sems_lib_AmAudioFile.td_fcto

#define sipEnum_AmAudioFile_OpenMode              sipModuleAPI_py_sems_lib.em_enums[0]

extern sipTypeDef sipType_py_sems_lib_AmAudioFile;

#endif
