/*
 * Interface header file.
 *
 * Generated by SIP 4.5.2 (4.5.2) on Mon Dec  8 15:20:56 2008
 */

#ifndef _py_sems_libPySemsB2ABEvent_h
#define _py_sems_libPySemsB2ABEvent_h

#line 117 "PySemsB2ABDialog.sip"
#include "../PySemsB2ABDialog.h"
#line 13 "sippy_sems_libPySemsB2ABEvent.h"

#define sipClass_PySemsB2ABEvent             sipModuleAPI_py_sems_lib.em_types[0]
#define sipCast_PySemsB2ABEvent              sipType_py_sems_lib_PySemsB2ABEvent.td_cast
#define sipForceConvertTo_PySemsB2ABEvent    sipType_py_sems_lib_PySemsB2ABEvent.td_fcto

extern sipTypeDef sipType_py_sems_lib_PySemsB2ABEvent;

#endif
