/*
 * Interface header file.
 *
 * Generated by SIP 4.1.1 (4.1.1-255) on Fri Feb  9 10:28:23 2007
 */

#ifndef _py_semsAmSipRequest_h
#define	_py_semsAmSipRequest_h

#line 6 "AmSipRequest.sip"
#include "../../../core/AmSipRequest.h"
#line 13 "sippy_semsAmSipRequest.h"

#include "sippy_semsstring.h"


#define	sipClass_AmSipRequest	sipModuleAPI_py_sems.em_types[3]
#define	sipCast_AmSipRequest	sipType_AmSipRequest.td_cast
#define	sipForceConvertTo_AmSipRequest	sipType_AmSipRequest.td_fcto

extern sipTypeDef sipType_AmSipRequest;

#endif
