/*
 * Interface header file.
 *
 * Generated by SIP 4.1.1 (4.1.1-255) on Mon Feb 19 14:57:35 2007
 */

#ifndef _py_sems_libAmAudioFile_h
#define	_py_sems_libAmAudioFile_h

#line 51 "AmAudio.sip"
#include "../../../core/AmAudio.h"
#line 13 "sippy_sems_libAmAudioFile.h"

#include "sippy_sems_libstring.h"


#define	sipClass_AmAudioFile	sipModuleAPI_py_sems_lib.em_types[1]
#define	sipCast_AmAudioFile	sipType_AmAudioFile.td_cast
#define	sipForceConvertTo_AmAudioFile	sipType_AmAudioFile.td_fcto

extern sipTypeDef sipType_AmAudioFile;

#endif
