/*
 * Interface header file.
 *
 * Generated by SIP 4.1.1 (4.1.1-255) on Mon Feb 19 14:57:35 2007
 */

#ifndef _py_sems_libPySemsDialog_h
#define	_py_sems_libPySemsDialog_h

#line 6 "PySemsDialog.sip"
#include "../PySems.h"
#line 13 "sippy_sems_libPySemsDialog.h"

#include "sippy_sems_libAmSipDialog.h"
#include "sippy_sems_libAmEvent.h"
#include "sippy_sems_libAmAudioFile.h"
#include "sippy_sems_libAmSipRequest.h"
#include "sippy_sems_libstring.h"


#define	sipClass_PySemsDialog	sipModuleAPI_py_sems_lib.em_types[0]
#define	sipCast_PySemsDialog	sipType_PySemsDialog.td_cast
#define	sipForceConvertTo_PySemsDialog	sipType_PySemsDialog.td_fcto

extern sipTypeDef sipType_PySemsDialog;


class sipPySemsDialog : public PySemsDialog
{
public:
	sipPySemsDialog();
	virtual ~sipPySemsDialog();

	/*
	 * There is a public method for every virtual method visible from
	 * this class.
	 */
	void onInvite(const AmSipRequest&);
	void onSessionStart(const AmSipRequest&);
	void onCancel();
	void onBye(const AmSipRequest&);
	void onDtmf(int,int);
	void process(AmEvent *);

	sipWrapper *sipPySelf;

private:
	sipPySemsDialog(const sipPySemsDialog &);
	sipPySemsDialog &operator = (const sipPySemsDialog &);

	sipMethodCache sipPyMethods[6];
};

#endif
