/*
 * Interface header file.
 *
 * Generated by SIP 4.5.2 (4.5.2) on Mon Dec  8 15:20:56 2008
 */

#ifndef _py_sems_libAmSipDialog_h
#define _py_sems_libAmSipDialog_h

#line 6 "AmSipDialog.sip"
#include "../../../core/AmSipDialog.h"
#line 13 "sippy_sems_libAmSipDialog.h"

#define sipClass_AmSipDialog             sipModuleAPI_py_sems_lib.em_types[10]
#define sipCast_AmSipDialog              sipType_py_sems_lib_AmSipDialog.td_cast
#define sipForceConvertTo_AmSipDialog    sipType_py_sems_lib_AmSipDialog.td_fcto

#define sipEnum_AmSipDialog_Status              sipModuleAPI_py_sems_lib.em_enums[2]

extern sipTypeDef sipType_py_sems_lib_AmSipDialog;

#endif
