/*
 * Interface header file.
 *
 * Generated by SIP 4.1.1 (4.1.1-255) on Fri Feb  9 10:28:23 2007
 */

#ifndef _py_semsAmSipDialog_h
#define	_py_semsAmSipDialog_h

#line 6 "AmSipDialog.sip"
#include "../../../core/AmSipDialog.h"
#line 13 "sippy_semsAmSipDialog.h"

#include "sippy_semsstring.h"
#include "sippy_semsAmSipRequest.h"
#include "sippy_semsAmSipReply.h"


#define	sipClass_AmSipDialog	sipModuleAPI_py_sems.em_types[1]
#define	sipCast_AmSipDialog	sipType_AmSipDialog.td_cast
#define	sipForceConvertTo_AmSipDialog	sipType_AmSipDialog.td_fcto

extern sipTypeDef sipType_AmSipDialog;

#endif
