/*
 * Interface wrapper code.
 *
 * Generated by SIP 4.5.2 (4.5.2) on Wed Mar 28 22:59:14 2007
 */

#include "sipAPIpy_sems_lib.h"
#include "sippy_sems_libPySemsDialog.h"

#include "sippy_sems_libAmSipDialog.h"
#include "sippy_sems_libPySemsDialog.h"
#include "sippy_sems_libAmEvent.h"
#include "sippy_sems_libAmAudioFile.h"
#include "sippy_sems_libAmSipRequest.h"
#include "sippy_sems_libstring.h"


sipPySemsDialog::sipPySemsDialog(): PySemsDialog(), sipPySelf(0)
{
    sipTrace(SIP_TRACE_CTORS,"sipPySemsDialog::sipPySemsDialog() (this=0x%08x)\n",this);

    sipCommonCtor(sipPyMethods,6);
}

sipPySemsDialog::~sipPySemsDialog()
{
    sipTrace(SIP_TRACE_DTORS,"sipPySemsDialog::~sipPySemsDialog() (this=0x%08x)\n",this);

    sipCommonDtor(sipPySelf);
}

void sipPySemsDialog::onInvite(const AmSipRequest& a0)
{
    sipTrace(SIP_TRACE_CATCHERS,"void sipPySemsDialog::onInvite(const AmSipRequest&) (this=0x%08x)\n",this);

    extern void sipVH_py_sems_lib_2(sip_gilstate_t,PyObject *,const AmSipRequest&);

    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[0],sipPySelf,NULL,sipNm_py_sems_lib_onInvite);

    if (!meth)
    {
        PySemsDialog::onInvite(a0);
        return;
    }

    sipVH_py_sems_lib_2(sipGILState,meth,a0);
}

void sipPySemsDialog::onSessionStart(const AmSipRequest& a0)
{
    sipTrace(SIP_TRACE_CATCHERS,"void sipPySemsDialog::onSessionStart(const AmSipRequest&) (this=0x%08x)\n",this);

    extern void sipVH_py_sems_lib_2(sip_gilstate_t,PyObject *,const AmSipRequest&);

    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[1],sipPySelf,NULL,sipNm_py_sems_lib_onSessionStart);

    if (!meth)
    {
        PySemsDialog::onSessionStart(a0);
        return;
    }

    sipVH_py_sems_lib_2(sipGILState,meth,a0);
}

void sipPySemsDialog::onCancel()
{
    sipTrace(SIP_TRACE_CATCHERS,"void sipPySemsDialog::onCancel() (this=0x%08x)\n",this);

    extern void sipVH_py_sems_lib_3(sip_gilstate_t,PyObject *);

    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[2],sipPySelf,NULL,sipNm_py_sems_lib_onCancel);

    if (!meth)
    {
        PySemsDialog::onCancel();
        return;
    }

    sipVH_py_sems_lib_3(sipGILState,meth);
}

void sipPySemsDialog::onBye(const AmSipRequest& a0)
{
    sipTrace(SIP_TRACE_CATCHERS,"void sipPySemsDialog::onBye(const AmSipRequest&) (this=0x%08x)\n",this);

    extern void sipVH_py_sems_lib_2(sip_gilstate_t,PyObject *,const AmSipRequest&);

    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[3],sipPySelf,NULL,sipNm_py_sems_lib_onBye);

    if (!meth)
    {
        PySemsDialog::onBye(a0);
        return;
    }

    sipVH_py_sems_lib_2(sipGILState,meth,a0);
}

void sipPySemsDialog::onDtmf(int a0,int a1)
{
    sipTrace(SIP_TRACE_CATCHERS,"void sipPySemsDialog::onDtmf(int,int) (this=0x%08x)\n",this);

    extern void sipVH_py_sems_lib_1(sip_gilstate_t,PyObject *,int,int);

    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[4],sipPySelf,NULL,sipNm_py_sems_lib_onDtmf);

    if (!meth)
    {
        PySemsDialog::onDtmf(a0,a1);
        return;
    }

    sipVH_py_sems_lib_1(sipGILState,meth,a0,a1);
}

void sipPySemsDialog::process(AmEvent *a0)
{
    sipTrace(SIP_TRACE_CATCHERS,"void sipPySemsDialog::process(AmEvent *) (this=0x%08x)\n",this);

    extern void sipVH_py_sems_lib_0(sip_gilstate_t,PyObject *,AmEvent *);

    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,&sipPyMethods[5],sipPySelf,NULL,sipNm_py_sems_lib_process);

    if (!meth)
    {
        PySemsDialog::process(a0);
        return;
    }

    sipVH_py_sems_lib_0(sipGILState,meth,a0);
}


extern "C" {static PyObject *meth_PySemsDialog_acceptAudio(PyObject *, PyObject *);}
static PyObject *meth_PySemsDialog_acceptAudio(PyObject *sipSelf,PyObject *sipArgs)
{
    sipTrace(SIP_TRACE_METHODS,"meth_PySemsDialog_acceptAudio()\n");

    int sipArgsParsed = 0;

    {
        const string * a0;
        int a0State = 0;
        const string * a1;
        int a1State = 0;
        string * a2;
        PySemsDialog *sipCpp;

        if (sipParseArgs(&sipArgsParsed,sipArgs,"BM1M1",&sipSelf,sipClass_PySemsDialog,&sipCpp,sipMappedType_string,&a0,&a0State,sipMappedType_string,&a1,&a1State))
        {
            int sipRes;
            a2 = new string();

            sipRes = sipCpp->acceptAudio(*a0,*a1,a2);

            sipReleaseMappedType(const_cast<string *>(a0),sipMappedType_string,a0State);
            sipReleaseMappedType(const_cast<string *>(a1),sipMappedType_string,a1State);

            return sipBuildResult(0,"(iD)",sipRes,a2,sipMappedType_string,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipArgsParsed,sipNm_py_sems_lib_PySemsDialog,sipNm_py_sems_lib_acceptAudio);

    return NULL;
}


extern "C" {static PyObject *meth_PySemsDialog_setStopped(PyObject *, PyObject *);}
static PyObject *meth_PySemsDialog_setStopped(PyObject *sipSelf,PyObject *sipArgs)
{
    sipTrace(SIP_TRACE_METHODS,"meth_PySemsDialog_setStopped()\n");

    int sipArgsParsed = 0;

    {
        PySemsDialog *sipCpp;

        if (sipParseArgs(&sipArgsParsed,sipArgs,"B",&sipSelf,sipClass_PySemsDialog,&sipCpp))
        {
            sipCpp->setStopped();

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipArgsParsed,sipNm_py_sems_lib_PySemsDialog,sipNm_py_sems_lib_setStopped);

    return NULL;
}


extern "C" {static PyObject *meth_PySemsDialog_onInvite(PyObject *, PyObject *);}
static PyObject *meth_PySemsDialog_onInvite(PyObject *sipSelf,PyObject *sipArgs)
{
    sipTrace(SIP_TRACE_METHODS,"meth_PySemsDialog_onInvite()\n");

    int sipArgsParsed = 0;
    bool sipSelfWasArg = !sipSelf;

    {
        const AmSipRequest * a0;
        PySemsDialog *sipCpp;

        if (sipParseArgs(&sipArgsParsed,sipArgs,"BJA",&sipSelf,sipClass_PySemsDialog,&sipCpp,sipClass_AmSipRequest,&a0))
        {
            (sipSelfWasArg ? sipCpp->PySemsDialog::onInvite(*a0) : sipCpp->onInvite(*a0));

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipArgsParsed,sipNm_py_sems_lib_PySemsDialog,sipNm_py_sems_lib_onInvite);

    return NULL;
}


extern "C" {static PyObject *meth_PySemsDialog_onSessionStart(PyObject *, PyObject *);}
static PyObject *meth_PySemsDialog_onSessionStart(PyObject *sipSelf,PyObject *sipArgs)
{
    sipTrace(SIP_TRACE_METHODS,"meth_PySemsDialog_onSessionStart()\n");

    int sipArgsParsed = 0;
    bool sipSelfWasArg = !sipSelf;

    {
        const AmSipRequest * a0;
        PySemsDialog *sipCpp;

        if (sipParseArgs(&sipArgsParsed,sipArgs,"BJA",&sipSelf,sipClass_PySemsDialog,&sipCpp,sipClass_AmSipRequest,&a0))
        {
            (sipSelfWasArg ? sipCpp->PySemsDialog::onSessionStart(*a0) : sipCpp->onSessionStart(*a0));

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipArgsParsed,sipNm_py_sems_lib_PySemsDialog,sipNm_py_sems_lib_onSessionStart);

    return NULL;
}


extern "C" {static PyObject *meth_PySemsDialog_onCancel(PyObject *, PyObject *);}
static PyObject *meth_PySemsDialog_onCancel(PyObject *sipSelf,PyObject *sipArgs)
{
    sipTrace(SIP_TRACE_METHODS,"meth_PySemsDialog_onCancel()\n");

    int sipArgsParsed = 0;
    bool sipSelfWasArg = !sipSelf;

    {
        PySemsDialog *sipCpp;

        if (sipParseArgs(&sipArgsParsed,sipArgs,"B",&sipSelf,sipClass_PySemsDialog,&sipCpp))
        {
            (sipSelfWasArg ? sipCpp->PySemsDialog::onCancel() : sipCpp->onCancel());

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipArgsParsed,sipNm_py_sems_lib_PySemsDialog,sipNm_py_sems_lib_onCancel);

    return NULL;
}


extern "C" {static PyObject *meth_PySemsDialog_onBye(PyObject *, PyObject *);}
static PyObject *meth_PySemsDialog_onBye(PyObject *sipSelf,PyObject *sipArgs)
{
    sipTrace(SIP_TRACE_METHODS,"meth_PySemsDialog_onBye()\n");

    int sipArgsParsed = 0;
    bool sipSelfWasArg = !sipSelf;

    {
        const AmSipRequest * a0;
        PySemsDialog *sipCpp;

        if (sipParseArgs(&sipArgsParsed,sipArgs,"BJA",&sipSelf,sipClass_PySemsDialog,&sipCpp,sipClass_AmSipRequest,&a0))
        {
            (sipSelfWasArg ? sipCpp->PySemsDialog::onBye(*a0) : sipCpp->onBye(*a0));

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipArgsParsed,sipNm_py_sems_lib_PySemsDialog,sipNm_py_sems_lib_onBye);

    return NULL;
}


extern "C" {static PyObject *meth_PySemsDialog_onDtmf(PyObject *, PyObject *);}
static PyObject *meth_PySemsDialog_onDtmf(PyObject *sipSelf,PyObject *sipArgs)
{
    sipTrace(SIP_TRACE_METHODS,"meth_PySemsDialog_onDtmf()\n");

    int sipArgsParsed = 0;
    bool sipSelfWasArg = !sipSelf;

    {
        int a0;
        int a1;
        PySemsDialog *sipCpp;

        if (sipParseArgs(&sipArgsParsed,sipArgs,"Bii",&sipSelf,sipClass_PySemsDialog,&sipCpp,&a0,&a1))
        {
            (sipSelfWasArg ? sipCpp->PySemsDialog::onDtmf(a0,a1) : sipCpp->onDtmf(a0,a1));

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipArgsParsed,sipNm_py_sems_lib_PySemsDialog,sipNm_py_sems_lib_onDtmf);

    return NULL;
}


extern "C" {static PyObject *meth_PySemsDialog_setInput(PyObject *, PyObject *);}
static PyObject *meth_PySemsDialog_setInput(PyObject *sipSelf,PyObject *sipArgs)
{
    sipTrace(SIP_TRACE_METHODS,"meth_PySemsDialog_setInput()\n");

    int sipArgsParsed = 0;

    {
        AmAudioFile * a0;
        PySemsDialog *sipCpp;

        if (sipParseArgs(&sipArgsParsed,sipArgs,"BJ@",&sipSelf,sipClass_PySemsDialog,&sipCpp,sipClass_AmAudioFile,&a0))
        {
            sipCpp->setInput(a0);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipArgsParsed,sipNm_py_sems_lib_PySemsDialog,sipNm_py_sems_lib_setInput);

    return NULL;
}


extern "C" {static PyObject *meth_PySemsDialog_setOutput(PyObject *, PyObject *);}
static PyObject *meth_PySemsDialog_setOutput(PyObject *sipSelf,PyObject *sipArgs)
{
    sipTrace(SIP_TRACE_METHODS,"meth_PySemsDialog_setOutput()\n");

    int sipArgsParsed = 0;

    {
        AmAudioFile * a0;
        PySemsDialog *sipCpp;

        if (sipParseArgs(&sipArgsParsed,sipArgs,"BJ@",&sipSelf,sipClass_PySemsDialog,&sipCpp,sipClass_AmAudioFile,&a0))
        {
            sipCpp->setOutput(a0);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipArgsParsed,sipNm_py_sems_lib_PySemsDialog,sipNm_py_sems_lib_setOutput);

    return NULL;
}


extern "C" {static PyObject *meth_PySemsDialog_setInOut(PyObject *, PyObject *);}
static PyObject *meth_PySemsDialog_setInOut(PyObject *sipSelf,PyObject *sipArgs)
{
    sipTrace(SIP_TRACE_METHODS,"meth_PySemsDialog_setInOut()\n");

    int sipArgsParsed = 0;

    {
        AmAudioFile * a0;
        AmAudioFile * a1;
        PySemsDialog *sipCpp;

        if (sipParseArgs(&sipArgsParsed,sipArgs,"BJ@J@",&sipSelf,sipClass_PySemsDialog,&sipCpp,sipClass_AmAudioFile,&a0,sipClass_AmAudioFile,&a1))
        {
            sipCpp->setInOut(a0,a1);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipArgsParsed,sipNm_py_sems_lib_PySemsDialog,sipNm_py_sems_lib_setInOut);

    return NULL;
}


extern "C" {static PyObject *meth_PySemsDialog_process(PyObject *, PyObject *);}
static PyObject *meth_PySemsDialog_process(PyObject *sipSelf,PyObject *sipArgs)
{
    sipTrace(SIP_TRACE_METHODS,"meth_PySemsDialog_process()\n");

    int sipArgsParsed = 0;
    bool sipSelfWasArg = !sipSelf;

    {
        AmEvent * a0;
        PySemsDialog *sipCpp;

        if (sipParseArgs(&sipArgsParsed,sipArgs,"BJ@",&sipSelf,sipClass_PySemsDialog,&sipCpp,sipClass_AmEvent,&a0))
        {
            (sipSelfWasArg ? sipCpp->PySemsDialog::process(a0) : sipCpp->process(a0));

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipArgsParsed,sipNm_py_sems_lib_PySemsDialog,sipNm_py_sems_lib_process);

    return NULL;
}


/* Cast a pointer to a type somewhere in its superclass hierarchy. */
extern "C" {static void *cast_PySemsDialog(void *, sipWrapperType *);}
static void *cast_PySemsDialog(void *ptr,sipWrapperType *targetClass)
{
    if (targetClass == sipClass_PySemsDialog)
        return ptr;

    return NULL;
}


/* Call the instance's destructor. */
extern "C" {static void release_PySemsDialog(void *, int);}
static void release_PySemsDialog(void *ptr,int state)
{
    if (state & SIP_DERIVED_CLASS)
        delete reinterpret_cast<sipPySemsDialog *>(ptr);
    else
        delete reinterpret_cast<PySemsDialog *>(ptr);
}


extern "C" {static void dealloc_PySemsDialog(sipWrapper *);}
static void dealloc_PySemsDialog(sipWrapper *sipSelf)
{
    sipTrace(SIP_TRACE_DEALLOCS,"dealloc_PySemsDialog()\n");

    if (sipIsDerived(sipSelf))
        reinterpret_cast<sipPySemsDialog *>(sipSelf->u.cppPtr)->sipPySelf = NULL;

    if (sipIsPyOwned(sipSelf))
    {
#line 17 "PySemsDialog.sip"
    fprintf(stderr,"------------- dealloc_PySemsDialog ----------\n");
#line 500 "sippy_sems_libPySemsDialog.cpp"

        release_PySemsDialog(sipSelf->u.cppPtr,sipSelf->flags);
    }
}


extern "C" {static void *init_PySemsDialog(sipWrapper *, PyObject *, sipWrapper **, int *);}
static void *init_PySemsDialog(sipWrapper *sipSelf,PyObject *sipArgs,sipWrapper **,int *sipArgsParsed)
{
    sipPySemsDialog *sipCpp = 0;

    sipTrace(SIP_TRACE_INITS,"init_PySemsDialog()\n");

    if (!sipCpp)
    {
        if (sipParseArgs(sipArgsParsed,sipArgs,""))
        {
            sipCpp = new sipPySemsDialog();
        }
    }

    if (sipCpp)
        sipCpp->sipPySelf = sipSelf;

    return sipCpp;
}


extern "C" {static PyObject *var_PySemsDialog_dlg(PyObject *, PyObject *);}
static PyObject *var_PySemsDialog_dlg(PyObject *sipSelf,PyObject *sipPy)
{
    int sipIsErr = 0;
   AmSipDialog *sipVal;
    PySemsDialog *sipCpp = reinterpret_cast<PySemsDialog *>(sipGetCppPtr((sipWrapper *)sipSelf,sipClass_PySemsDialog));

    if (!sipCpp)
        return NULL;

    if (sipPy == NULL)
    {
        sipVal = &sipCpp->dlg;

        sipPy = sipConvertFromInstance(sipVal,sipClass_AmSipDialog,NULL);

        return sipPy;
    }

    sipVal = reinterpret_cast<AmSipDialog *>(sipForceConvertToInstance(sipPy,sipClass_AmSipDialog,NULL,SIP_NOT_NONE,NULL,&sipIsErr));

    if (sipIsErr)
        return NULL;

    sipCpp->dlg = *sipVal;

    Py_INCREF(Py_None);
    return Py_None;
}

PyMethodDef variables_PySemsDialog[] = {
    {sipNm_py_sems_lib_dlg, var_PySemsDialog_dlg, 0, NULL},
    {0, 0, 0, 0}
};


extern "C" {static void *forceConvertTo_PySemsDialog(PyObject *, int *);}
static void *forceConvertTo_PySemsDialog(PyObject *valobj,int *iserrp)
{
    if (*iserrp || valobj == NULL)
        return NULL;

    if (valobj == Py_None || sipIsSubClassInstance(valobj,sipClass_PySemsDialog))
        return sipConvertToCpp(valobj,sipClass_PySemsDialog,iserrp);

    sipBadClass(sipNm_py_sems_lib_PySemsDialog);

    *iserrp = 1;

    return NULL;
}


static PyMethodDef methods_PySemsDialog[] = {
    {sipNm_py_sems_lib_acceptAudio, meth_PySemsDialog_acceptAudio, METH_VARARGS, NULL},
    {sipNm_py_sems_lib_onBye, meth_PySemsDialog_onBye, METH_VARARGS, NULL},
    {sipNm_py_sems_lib_onCancel, meth_PySemsDialog_onCancel, METH_VARARGS, NULL},
    {sipNm_py_sems_lib_onDtmf, meth_PySemsDialog_onDtmf, METH_VARARGS, NULL},
    {sipNm_py_sems_lib_onInvite, meth_PySemsDialog_onInvite, METH_VARARGS, NULL},
    {sipNm_py_sems_lib_onSessionStart, meth_PySemsDialog_onSessionStart, METH_VARARGS, NULL},
    {sipNm_py_sems_lib_process, meth_PySemsDialog_process, METH_VARARGS, NULL},
    {sipNm_py_sems_lib_setInOut, meth_PySemsDialog_setInOut, METH_VARARGS, NULL},
    {sipNm_py_sems_lib_setInput, meth_PySemsDialog_setInput, METH_VARARGS, NULL},
    {sipNm_py_sems_lib_setOutput, meth_PySemsDialog_setOutput, METH_VARARGS, NULL},
    {sipNm_py_sems_lib_setStopped, meth_PySemsDialog_setStopped, METH_VARARGS, NULL}
};


sipTypeDef sipType_py_sems_lib_PySemsDialog = {
    0,
    0,
    "py_sems_lib.PySemsDialog",
    0,
    {0, 0, 1},
    0,
    0,
    11, methods_PySemsDialog,
    0, 0,
    variables_PySemsDialog,
    init_PySemsDialog,
    0,
    0,
    0,
    0,
    0,
    0,
    dealloc_PySemsDialog,
    cast_PySemsDialog,
    release_PySemsDialog,
    forceConvertTo_PySemsDialog,
    0,
    0,
    {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    0
};
