/*
 * Interface header file.
 *
 * Generated by SIP 4.5.2 (4.5.2) on Mon Dec  8 15:20:56 2008
 */

#ifndef _py_sems_libPySemsB2BDialog_h
#define _py_sems_libPySemsB2BDialog_h

#line 6 "PySemsB2BDialog.sip"
#include "../PySemsB2BDialog.h"
#line 13 "sippy_sems_libPySemsB2BDialog.h"

#define sipClass_PySemsB2BDialog             sipModuleAPI_py_sems_lib.em_types[5]
#define sipCast_PySemsB2BDialog              sipType_py_sems_lib_PySemsB2BDialog.td_cast
#define sipForceConvertTo_PySemsB2BDialog    sipType_py_sems_lib_PySemsB2BDialog.td_fcto

extern sipTypeDef sipType_py_sems_lib_PySemsB2BDialog;


class sipPySemsB2BDialog : public PySemsB2BDialog
{
public:
    sipPySemsB2BDialog();
    virtual ~sipPySemsB2BDialog();

    /*
     * There is a protected method for every virtual method visible from
     * this class.
     */
protected:
    void onInvite(const AmSipRequest&);
    void onSessionStart(const AmSipRequest&);
    void onCancel();
    void onBye(const AmSipRequest&);
    void onDtmf(int,int);
    void process(AmEvent *);

public:
    sipWrapper *sipPySelf;

private:
    sipPySemsB2BDialog(const sipPySemsB2BDialog &);
    sipPySemsB2BDialog &operator = (const sipPySemsB2BDialog &);

    sipMethodCache sipPyMethods[6];
};

#endif
