/*
 * Interface header file.
 *
 * Generated by SIP 4.5.2 (4.5.2) on Thu Mar 29 00:29:43 2007
 */

#ifndef _py_sems_libPySemsDialog_h
#define _py_sems_libPySemsDialog_h

#line 6 "PySemsDialog.sip"
#include "../PySemsDialog.h"
#line 13 "sippy_sems_libPySemsDialog.h"

#define sipClass_PySemsDialog             sipModuleAPI_py_sems_lib.em_types[4]
#define sipCast_PySemsDialog              sipType_py_sems_lib_PySemsDialog.td_cast
#define sipForceConvertTo_PySemsDialog    sipType_py_sems_lib_PySemsDialog.td_fcto

extern sipTypeDef sipType_py_sems_lib_PySemsDialog;


class sipPySemsDialog : public PySemsDialog
{
public:
    sipPySemsDialog();
    virtual ~sipPySemsDialog();

    /*
     * There is a protected method for every virtual method visible from
     * this class.
     */
protected:
    void onInvite(const AmSipRequest&);
    void onSessionStart(const AmSipRequest&);
    void onCancel();
    void onBye(const AmSipRequest&);
    void onDtmf(int,int);
    void process(AmEvent *);

public:
    sipWrapper *sipPySelf;

private:
    sipPySemsDialog(const sipPySemsDialog &);
    sipPySemsDialog &operator = (const sipPySemsDialog &);

    sipMethodCache sipPyMethods[6];
};

#endif
