/*
 * Interface header file.
 *
 * Generated by SIP 4.1.1 (4.1.1-255) on Mon Feb 19 14:57:35 2007
 */

#ifndef _py_sems_libAmSipReply_h
#define	_py_sems_libAmSipReply_h

#line 6 "AmSipReply.sip"
#include "../../../core/AmSipReply.h"
#line 13 "sippy_sems_libAmSipReply.h"

#include "sippy_sems_libstring.h"


#define	sipClass_AmSipReply	sipModuleAPI_py_sems_lib.em_types[5]
#define	sipCast_AmSipReply	sipType_AmSipReply.td_cast
#define	sipForceConvertTo_AmSipReply	sipType_AmSipReply.td_fcto

extern sipTypeDef sipType_AmSipReply;

#endif
