/*
 * Interface header file.
 *
 * Generated by SIP 4.5.2 (4.5.2) on Mon Dec  8 15:20:56 2008
 */

#ifndef _py_sems_libAmSessionAudioConnector_h
#define _py_sems_libAmSessionAudioConnector_h

#line 5 "PySemsB2ABDialog.sip"
#include "../../../core/AmB2ABSession.h"
#line 13 "sippy_sems_libAmSessionAudioConnector.h"

#define sipClass_AmSessionAudioConnector             sipModuleAPI_py_sems_lib.em_types[4]
#define sipCast_AmSessionAudioConnector              sipType_py_sems_lib_AmSessionAudioConnector.td_cast
#define sipForceConvertTo_AmSessionAudioConnector    sipType_py_sems_lib_AmSessionAudioConnector.td_fcto

extern sipTypeDef sipType_py_sems_lib_AmSessionAudioConnector;

#endif
