/*
 * Interface header file.
 *
 * Generated by SIP 4.5.2 (4.5.2) on Mon Dec  8 15:20:56 2008
 */

#ifndef _py_sems_libAmEvent_h
#define _py_sems_libAmEvent_h

#line 5 "AmAudio.sip"
#include "../../../core/AmEvent.h"
#line 13 "sippy_sems_libAmEvent.h"

#define sipClass_AmEvent             sipModuleAPI_py_sems_lib.em_types[8]
#define sipCast_AmEvent              sipType_py_sems_lib_AmEvent.td_cast
#define sipForceConvertTo_AmEvent    sipType_py_sems_lib_AmEvent.td_fcto

extern sipTypeDef sipType_py_sems_lib_AmEvent;


class sipAmEvent : public AmEvent
{
public:
    sipAmEvent(int);
    sipAmEvent(const AmEvent&);
    ~sipAmEvent();

public:
    sipWrapper *sipPySelf;

private:
    sipAmEvent(const sipAmEvent &);
    sipAmEvent &operator = (const sipAmEvent &);
};

#endif
