/*
 * Interface header file.
 *
 * Generated by SIP 4.5.2 (4.5.2) on Mon Dec  8 15:20:56 2008
 */

#ifndef _py_sems_libAmSipReply_h
#define _py_sems_libAmSipReply_h

#line 6 "AmSipReply.sip"
#include "../../../core/AmSipMsg.h"
#line 13 "sippy_sems_libAmSipReply.h"

#define sipClass_AmSipReply             sipModuleAPI_py_sems_lib.em_types[11]
#define sipCast_AmSipReply              sipType_py_sems_lib_AmSipReply.td_cast
#define sipForceConvertTo_AmSipReply    sipType_py_sems_lib_AmSipReply.td_fcto

extern sipTypeDef sipType_py_sems_lib_AmSipReply;

#endif
