/*
 * Interface header file.
 *
 * Generated by SIP 4.5.2 (4.5.2) on Thu Mar 29 00:29:43 2007
 */

#ifndef _py_sems_libstring_h
#define _py_sems_libstring_h



#line 4 "string.sip"
#include <string>
using std::string;
#line 16 "sippy_sems_libstring.h"

#define sipMappedType_string        &sipMappedTypeDef_string
#define sipForceConvertTo_string    sipMappedTypeDef_string.mt_fcto
#define sipConvertFrom_string       sipMappedTypeDef_string.mt_cfrom

extern sipMappedType sipMappedTypeDef_string;

#endif
