/*
 * Interface header file.
 *
 * Generated by SIP 4.5.2 (4.5.2) on Tue Oct 16 13:58:18 2007
 */

#ifndef _py_sems_libAmSipRequest_h
#define _py_sems_libAmSipRequest_h

#line 6 "AmSipRequest.sip"
#include "../../../core/AmSipMsg.h"
#line 13 "sippy_sems_libAmSipRequest.h"

#define sipClass_AmSipRequest             sipModuleAPI_py_sems_lib.em_types[11]
#define sipCast_AmSipRequest              sipType_py_sems_lib_AmSipRequest.td_cast
#define sipForceConvertTo_AmSipRequest    sipType_py_sems_lib_AmSipRequest.td_fcto

extern sipTypeDef sipType_py_sems_lib_AmSipRequest;

#endif
