/*
 * Interface header file.
 *
 * Generated by SIP 4.1.1 (4.1.1-255) on Fri Feb  9 10:28:23 2007
 */

#ifndef _py_semsPySemsDialog_h
#define	_py_semsPySemsDialog_h

#line 6 "PySemsDialog.sip"
#include "../PySems.h"
#line 13 "sippy_semsPySemsDialog.h"

#include "sippy_semsAmSipDialog.h"
#include "sippy_semsAmSipReply.h"
#include "sippy_semsAmSipRequest.h"
#include "sippy_semsstring.h"


#define	sipClass_PySemsDialog	sipModuleAPI_py_sems.em_types[0]
#define	sipCast_PySemsDialog	sipType_PySemsDialog.td_cast
#define	sipForceConvertTo_PySemsDialog	sipType_PySemsDialog.td_fcto

extern sipTypeDef sipType_PySemsDialog;


class sipPySemsDialog : public PySemsDialog
{
public:
	sipPySemsDialog();
	virtual ~sipPySemsDialog();

	/*
	 * There is a public method for every virtual method visible from
	 * this class.
	 */
	void onInvite(const AmSipRequest&);
	void onSessionStart(const AmSipRequest&);
	void onBye(const AmSipRequest&);
	void onCancel();
	void onDtmf(int,int);
	void onOtherBye(const AmSipRequest&);
	void onOtherReply(const AmSipReply&);

	sipWrapper *sipPySelf;

private:
	sipPySemsDialog(const sipPySemsDialog &);
	sipPySemsDialog &operator = (const sipPySemsDialog &);

	sipMethodCache sipPyMethods[7];
};

#endif
