/*
 * Interface header file.
 *
 * Generated by SIP 4.1.1 (4.1.1-255) on Mon Feb 19 14:57:35 2007
 */

#ifndef _py_sems_libAmSipDialog_h
#define	_py_sems_libAmSipDialog_h

#line 6 "AmSipDialog.sip"
#include "../../../core/AmSipDialog.h"
#line 13 "sippy_sems_libAmSipDialog.h"

#include "sippy_sems_libstring.h"
#include "sippy_sems_libAmSipRequest.h"
#include "sippy_sems_libAmSipReply.h"


#define	sipClass_AmSipDialog	sipModuleAPI_py_sems_lib.em_types[4]
#define	sipCast_AmSipDialog	sipType_AmSipDialog.td_cast
#define	sipForceConvertTo_AmSipDialog	sipType_AmSipDialog.td_fcto

extern sipTypeDef sipType_AmSipDialog;

#endif
