/*
 * Interface wrapper code.
 *
 * Generated by SIP 4.5.2 (4.5.2) on Mon Dec  8 15:20:56 2008
 */

#include "sipAPIpy_sems_lib.h"
#include "sippy_sems_libPySemsB2ABEvent.h"


/* Cast a pointer to a type somewhere in its superclass hierarchy. */
extern "C" {static void *cast_PySemsB2ABEvent(void *, sipWrapperType *);}
static void *cast_PySemsB2ABEvent(void *ptr,sipWrapperType *targetClass)
{
    if (targetClass == sipClass_PySemsB2ABEvent)
        return ptr;

    return NULL;
}


/* Call the instance's destructor. */
extern "C" {static void release_PySemsB2ABEvent(void *, int);}
static void release_PySemsB2ABEvent(void *ptr,int)
{
    delete reinterpret_cast<PySemsB2ABEvent *>(ptr);
}


extern "C" {static void dealloc_PySemsB2ABEvent(sipWrapper *);}
static void dealloc_PySemsB2ABEvent(sipWrapper *sipSelf)
{
    sipTrace(SIP_TRACE_DEALLOCS,"dealloc_PySemsB2ABEvent()\n");

    if (sipIsPyOwned(sipSelf))
    {
        release_PySemsB2ABEvent(sipSelf->u.cppPtr,0);
    }
}


extern "C" {static void *init_PySemsB2ABEvent(sipWrapper *, PyObject *, sipWrapper **, int *);}
static void *init_PySemsB2ABEvent(sipWrapper *,PyObject *sipArgs,sipWrapper **,int *sipArgsParsed)
{
    PySemsB2ABEvent *sipCpp = 0;

    sipTrace(SIP_TRACE_INITS,"init_PySemsB2ABEvent()\n");

    if (!sipCpp)
    {
        int a0;

        if (sipParseArgs(sipArgsParsed,sipArgs,"i",&a0))
        {
            sipCpp = new PySemsB2ABEvent(a0);
        }
    }

    if (!sipCpp)
    {
        const PySemsB2ABEvent * a0;

        if (sipParseArgs(sipArgsParsed,sipArgs,"JA",sipClass_PySemsB2ABEvent,&a0))
        {
            sipCpp = new PySemsB2ABEvent(*a0);
        }
    }

    return sipCpp;
}


extern "C" {static void *forceConvertTo_PySemsB2ABEvent(PyObject *, int *);}
static void *forceConvertTo_PySemsB2ABEvent(PyObject *valobj,int *iserrp)
{
    if (*iserrp || valobj == NULL)
        return NULL;

    if (valobj == Py_None || sipIsSubClassInstance(valobj,sipClass_PySemsB2ABEvent))
        return sipConvertToCpp(valobj,sipClass_PySemsB2ABEvent,iserrp);

    sipBadClass(sipNm_py_sems_lib_PySemsB2ABEvent);

    *iserrp = 1;

    return NULL;
}


sipTypeDef sipType_py_sems_lib_PySemsB2ABEvent = {
    0,
    0,
    "py_sems_lib.PySemsB2ABEvent",
    0,
    {0, 0, 1},
    0,
    0,
    0, 0,
    0, 0,
    0,
    init_PySemsB2ABEvent,
    0,
    0,
    0,
    0,
    0,
    0,
    dealloc_PySemsB2ABEvent,
    cast_PySemsB2ABEvent,
    release_PySemsB2ABEvent,
    forceConvertTo_PySemsB2ABEvent,
    0,
    0,
    {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    0
};
