/*
 * Interface header file.
 *
 * Generated by SIP 4.1.1 (4.1.1-255) on Mon Feb 19 14:57:35 2007
 */

#ifndef _py_sems_libstring_h
#define	_py_sems_libstring_h



#line 4 "string.sip"
#include <string>
using std::string;
#line 16 "sippy_sems_libstring.h"


#define	sipForceConvertTo_string	sipMappedType_string.mt_fcto
#define	sipConvertTo_string	sipMappedType_string.mt_cto
#define	sipConvertFrom_string	sipMappedType_string.mt_cfrom

extern sipMappedTypeDef sipMappedType_string;

#endif
