
plug_in_name = jukecall

module_ldflags =
module_cflags  = 

module_extra_objs = 
extra_install = jukecall_audio 

extra_clean = 

COREPATH ?=../../../core
include $(COREPATH)/plug-in/Makefile.app_module

