find_path(ILBC_INCLUDE_DIR ilbc.h)
find_library(ILBC_LIBRARIES NAMES ilbc)

if(ILBC_INCLUDE_DIR AND ILBC_LIBRARIES)
  set(ILBC_FOUND TRUE)
endif(ILBC_INCLUDE_DIR AND ILBC_LIBRARIES)

if(ILBC_FOUND)
  if(NOT Ilbc_FIND_QUIETLY)
    message(STATUS "Found ilbc includes:	${ILBC_INCLUDE_DIR}/ilbc.h")
    message(STATUS "Found ilbc library: ${ILBC_LIBRARIES}")
  endif(NOT Ilbc_FIND_QUIETLY)
else(ILBC_FOUND)
  if(Ilbc_FIND_REQUIRED)
    message(FATAL_ERROR "Could NOT find ilbc development files")
  endif(Ilbc_FIND_REQUIRED)
endif(ILBC_FOUND)
