find_path(GSM_INCLUDE_DIR gsm.h)
find_library(GSM_LIBRARIES NAMES gsm)

if(GSM_INCLUDE_DIR AND GSM_LIBRARIES)
  set(GSM_FOUND TRUE)
endif(GSM_INCLUDE_DIR AND GSM_LIBRARIES)

if(GSM_FOUND)
  if(NOT Gsm_FIND_QUIETLY)
    message(STATUS "Found gsm includes:	${GSM_INCLUDE_DIR}/gsm.h")
    message(STATUS "Found gsm library: ${GSM_LIBRARIES}")
  endif(NOT Gsm_FIND_QUIETLY)
else(GSM_FOUND)
  if(Gsm_FIND_REQUIRED)
    message(FATAL_ERROR "Could NOT find gsm development files")
  endif(Gsm_FIND_REQUIRED)
endif(GSM_FOUND)
