find_path(OPUS_INCLUDE_DIR opus/opus.h)
find_library(OPUS_LIBRARIES NAMES opus)

if(OPUS_INCLUDE_DIR AND OPUS_LIBRARIES)
  set(OPUS_FOUND TRUE)
endif(OPUS_INCLUDE_DIR AND OPUS_LIBRARIES)

if(OPUS_FOUND)
  if(NOT Opus_FIND_QUIETLY)
    message(STATUS "Found Opus includes:	${OPUS_INCLUDE_DIR}/opus/opus.h")
    message(STATUS "Found Opus library: ${OPUS_LIBRARIES}")
  endif(NOT Opus_FIND_QUIETLY)
else(OPUS_FOUND)
  if(Opus_FIND_REQUIRED)
    message(FATAL_ERROR "Could NOT find opus development files")
  endif(Opus_FIND_REQUIRED)
endif(OPUS_FOUND)
