find_path(LIBEV_INCLUDE_DIR ev.h HINTS /usr/include/libev)
find_library(LIBEV_LIBRARIES NAMES ev)

if(LIBEV_INCLUDE_DIR AND LIBEV_LIBRARIES)
  set(LIBEV_FOUND TRUE)
endif(LIBEV_INCLUDE_DIR AND LIBEV_LIBRARIES)

if(LIBEV_FOUND)
  if(NOT Libev_FIND_QUIETLY)
    message(STATUS "Found libev includes:	${LIBEV_INCLUDE_DIR}/libev/ev.h")
    message(STATUS "Found libev library: ${LIBEV_LIBRARIES}")
  endif(NOT Libev_FIND_QUIETLY)
else(LIBEV_FOUND)
  if(Libev_FIND_REQUIRED)
    message(FATAL_ERROR "Could NOT find libev development files")
  endif(Libev_FIND_REQUIRED)
endif(LIBEV_FOUND)
