find_path(FLITE_INCLUDE_DIR flite/flite.h)
find_library(FLITE_LIBRARIES NAMES flite)

if(FLITE_INCLUDE_DIR AND FLITE_LIBRARIES)
  set(FLITE_FOUND TRUE)
endif(FLITE_INCLUDE_DIR AND FLITE_LIBRARIES)

if(FLITE_FOUND)
  if(NOT Flite_FIND_QUIETLY)
    message(STATUS "Found flite includes:	${FLITE_INCLUDE_DIR}/flite/flite.h")
    message(STATUS "Found flite library: ${FLITE_LIBRARIES}")
  endif(NOT Flite_FIND_QUIETLY)
else(FLITE_FOUND)
  if(Flite_FIND_REQUIRED)
    message(FATAL_ERROR "Could NOT find flite development files")
  endif(Flite_FIND_REQUIRED)
endif(FLITE_FOUND)
