find_path(SPANDSP_INCLUDE_DIR spandsp.h)
find_library(SPANDSP_LIBRARIES NAMES spandsp)

if(SPANDSP_INCLUDE_DIR AND SPANDSP_LIBRARIES)
  set(SPANDSP_FOUND TRUE)
endif(SPANDSP_INCLUDE_DIR AND SPANDSP_LIBRARIES)

if(SPANDSP_FOUND)
  if(NOT Spandsp_FIND_QUIETLY)
    message(STATUS "Found spandsp includes:	${SPANDSP_INCLUDE_DIR}/spandsp.h")
    message(STATUS "Found spandsp library: ${SPANDSP_LIBRARIES}")
  endif(NOT Spandsp_FIND_QUIETLY)
else(SPANDSP_FOUND)
  if(Spandsp_FIND_REQUIRED)
    message(FATAL_ERROR "Could NOT find spandsp development files")
  endif(Spandsp_FIND_REQUIRED)
endif(SPANDSP_FOUND)
