find_path(SPEEX_INCLUDE_DIR speex/speex.h)
find_library(SPEEX_LIBRARIES NAMES speex)

if(SPEEX_INCLUDE_DIR AND SPEEX_LIBRARIES)
  set(SPEEX_FOUND TRUE)
endif(SPEEX_INCLUDE_DIR AND SPEEX_LIBRARIES)

if(SPEEX_FOUND)
  if(NOT Speex_FIND_QUIETLY)
    message(STATUS "Found speex includes:	${SPEEX_INCLUDE_DIR}/speex/speex.h")
    message(STATUS "Found speex library: ${SPEEX_LIBRARIES}")
  endif(NOT Speex_FIND_QUIETLY)
else(SPEEX_FOUND)
  if(Speex_FIND_REQUIRED)
    message(FATAL_ERROR "Could NOT find speex development files")
  endif(Speex_FIND_REQUIRED)
endif(SPEEX_FOUND)
