find_path(RTMP_INCLUDE_DIR librtmp/rtmp.h)
find_library(RTMP_LIBRARIES NAMES rtmp)

if(RTMP_INCLUDE_DIR AND RTMP_LIBRARIES)
  set(RTMP_FOUND TRUE)
endif(RTMP_INCLUDE_DIR AND RTMP_LIBRARIES)

if(RTMP_FOUND)
  if(NOT Librtmp_FIND_QUIETLY)
    message(STATUS "Found rtmp includes:	${RTMP_INCLUDE_DIR}/rtmp.h")
    message(STATUS "Found rtmp library: ${RTMP_LIBRARIES}")
  endif(NOT Librtmp_FIND_QUIETLY)
else(RTMP_FOUND)
  if(Librtmp_FIND_REQUIRED)
    message(FATAL_ERROR "Could NOT find rtmp development files")
  endif(Librtmp_FIND_REQUIRED)
endif(RTMP_FOUND)
