find_package(OpenDIS CONFIG QUIET)

set(OPENDIS_FOUND FALSE)
set(OPENDIS_INCLUDE_DIRS "")
set(OPENDIS_LIBRARIES "")

if(TARGET OpenDIS6)
  set(OPENDIS_FOUND TRUE)
  list(APPEND OPENDIS_LIBRARIES OpenDIS6)
elseif(TARGET OpenDIS::OpenDIS6)
  set(OPENDIS_FOUND TRUE)
  list(APPEND OPENDIS_LIBRARIES OpenDIS::OpenDIS6)
elseif(TARGET OpenDIS::DIS6)
  set(OPENDIS_FOUND TRUE)
  list(APPEND OPENDIS_LIBRARIES OpenDIS::DIS6)
endif()

if(NOT OPENDIS_FOUND)
  if(CMAKE_SYSTEM_NAME STREQUAL "FreeBSD")
    find_path(OPENDIS_INCLUDE_DIRS dis6/EntityStatePdu.h HINTS /usr/local/include)
    find_library(OPENDIS_LIB NAMES OpenDIS6 opendis6 HINTS /usr/local/lib)
  else()
    find_path(OPENDIS_INCLUDE_DIRS dis6/EntityStatePdu.h HINTS /usr/include /usr/local/include)
    find_library(OPENDIS_LIB NAMES OpenDIS6 opendis6 HINTS /usr/lib /usr/local/lib /usr/lib64 /usr/local/lib64)
  endif()

  if(OPENDIS_INCLUDE_DIRS AND OPENDIS_LIB)
    set(OPENDIS_FOUND TRUE)
    list(APPEND OPENDIS_LIBRARIES ${OPENDIS_LIB})
  endif()
endif()

if(OPENDIS_FOUND)
  if(NOT OpenDIS_FIND_QUIETLY)
    if(OPENDIS_INCLUDE_DIRS)
      message(STATUS "Found OpenDIS includes: ${OPENDIS_INCLUDE_DIRS}/dis6/EntityStatePdu.h")
    endif()
    message(STATUS "Found OpenDIS library: ${OPENDIS_LIBRARIES}")
  endif()
else()
  if(OpenDIS_FIND_REQUIRED)
    message(FATAL_ERROR "Could NOT find OpenDIS6 development files")
  endif()
endif()
