find_path(LIBZRTP_INCLUDE_DIR zrtp.h HINTS /usr/include/zrtp)
find_library(LIBZRTP_LIBRARIES NAMES zrtp)

if(LIBZRTP_INCLUDE_DIR AND LIBZRTP_LIBRARIES)
  set(LIBZRTP_FOUND TRUE)
endif(LIBZRTP_INCLUDE_DIR AND LIBZRTP_LIBRARIES)

if(LIBZRTP_FOUND)
  if(NOT Libzrtp_FIND_QUIETLY)
    message(STATUS "Found libzrtp includes:	${LIBZRTP_INCLUDE_DIR}/zrtp/zrtp.h")
    message(STATUS "Found libzrtp library: ${LIBZRTP_LIBRARIES}")
  endif(NOT Libzrtp_FIND_QUIETLY)
else(LIBZRTP_FOUND)
  if(Libzrtp_FIND_REQUIRED)
    message(FATAL_ERROR "Could NOT find libzrtp development files")
  endif(Libzrtp_FIND_REQUIRED)
endif(LIBZRTP_FOUND)
