find_path(MISDN_INCLUDE_DIR mISDNuser/mISDNlib.h)
find_library(MISDN_LIBRARIES NAMES mISDN)

if(MISDN_INCLUDE_DIR AND MISDN_LIBRARIES)
  set(MISDN_FOUND TRUE)
endif(MISDN_INCLUDE_DIR AND MISDN_LIBRARIES)

if(MISDN_FOUND)
  if(NOT MISDN_FIND_QUIETLY)
    message(
      STATUS "Found mISDN includes:	${MISDN_INCLUDE_DIR}/mISDNuser/mISDNlib.h")
    message(STATUS "Found mISDN library: ${MISDN_LIBRARIES}")
  endif(NOT MISDN_FIND_QUIETLY)
else(MISDN_FOUND)
  if(MISDN_FIND_REQUIRED)
    message(FATAL_ERROR "Could NOT find mISDN development files")
  endif(MISDN_FIND_REQUIRED)
endif(MISDN_FOUND)
