#!/usr/bin/python
# -*- coding: utf-8 -*-
import sys
from xmlrpclib import *

if len(sys.argv) != 4:
	print "usage: %s <room> <participant_id> <number>" % sys.argv[0]
	sys.exit(1)

s = ServerProxy('http://localhost:8090')
print "Active calls: %d" % s.calls()
print s.di('webconference','addParticipant', sys.argv[1], sys.argv[2], sys.argv[3])
