# Python version: 2.5, 2.4 or 2.3
#
PYTHON_VERSION ?= $(shell python -c 'import sys;print sys.version[0:3]')

PY_VER = $(PYTHON_VERSION)
PY_EXE = python$(PY_VER)

# For flite text-to-speech set TTS = y
#
TTS ?= n

FLITE_DIR = /usr/src/flite-1.2-release
ALT_FLITE_DIR = /usr/include/flite
