# Python version: 2.5, 2.4 or 2.3
#
PYTHON_VERSION ?= `python -c 'import sys;print sys.version[0:3]';`

# For flite text-to-speech set TTS = y
#
TTS ?= n

FLITE_DIR = /usr/src/flite-1.2-release
ALT_FLITE_DIR = /usr/include/flite
